// V65: provider setup wizard, unified runtime hook, modern session strip and integration diagnostics.
(function(){
 const ENDPOINT_KEY='hw-proxy-endpoint-v1', PROVIDER_KEY='hw-data-provider-v1';
 function endpoint(){return (localStorage.getItem(ENDPOINT_KEY)||'').trim().replace(/\/$/,'')}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 async function getJSON(path,timeout=7000){const base=endpoint();if(!base)throw new Error('proxy_endpoint_not_configured');const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(base+path,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||`http_${r.status}`);return p}finally{clearTimeout(timer)}}
 // Establish one hook point for future V65+ features, instead of wrapping renderAll repeatedly.
 if(!window.ProductRuntime){
  const hooks=[];
  window.ProductRuntime={afterRender(fn){if(typeof fn==='function'&&!hooks.includes(fn))hooks.push(fn)},run(){hooks.slice().forEach(fn=>{try{fn()}catch(e){console.warn('ProductRuntime hook failed',e)}})}};
  const currentRender=renderAll;
  renderAll=function(){currentRender();ProductRuntime.run()};
 }
 function sessionStrip(){if(!window.MarketSessionService)return'';const picks=[['上证指数','A股'],['恒生指数','港股'],['日经225','日本'],['KOSPI','韩国'],['德国DAX','欧洲'],['纳斯达克100','美股']];return `<div class="v65-sessions"><div class="section-head"><b>全球交易状态</b><span>按市场本地时间自动判断</span></div><div class="v65-session-grid">${picks.map(([name,label])=>{const x=assets.find(a=>a.name===name)||({code:label==='美股'?'NVDA':label==='日本'?'7203.T':label==='韩国'?'005930.KS':label==='欧洲'?'SAP.DE':label==='港股'?'0700.HK':'600519',tag:label,region:label});const s=MarketSessionService.status(x),cal=ExchangeCalendar?.info?.(s.kind),calReady=!!cal?.count;return `<div><i class="${s.open?'open':'closed'}"></i><b>${label}</b><span>${s.status}</span><small>${calReady?s.note:'常规时段估算'}</small></div>`}).join('')}</div><small class="v65-session-note">未加载可信交易所节假日日历的市场，只按工作日和常规交易时段估算。</small></div>`}
 function installSessionStrip(){if(state.page!=='首页')return;const c=el('content');if(!c)return;c.querySelector('.live-sessions')?.remove();c.querySelector('.v65-sessions')?.remove();const anchor=c.querySelector('.market-pulse')||c.firstElementChild;anchor?.insertAdjacentHTML('afterend',sessionStrip())}
 function wizardCard(){const ep=endpoint(),active=MarketDataService?.provider||'mock',cap=GatewayCapabilityService?.cached?.(),configured=!!ep,healthy=!!cap?.ok;const us=cap?.providers?.US;return `<div class="v65-wizard"><div class="section-head"><b>真实行情接入向导</b><span>V65</span></div><div class="v65-step ${configured?'done':''}"><i>1</i><div><b>填写网关地址</b><span>${configured?esc(ep):'尚未配置 HTTP Proxy 地址'}</span></div><em>${configured?'完成':'待完成'}</em></div><div class="v65-step ${healthy?'done':''}"><i>2</i><div><b>检测网关能力</b><span>${healthy?`Gateway V${esc(cap.version||'—')} · ${esc((cap.scope||[]).join('/'))||'未声明市场'}`:'读取 /health 确认后端是否可用'}</span></div><em>${healthy?'完成':'待检测'}</em></div><div class="v65-step ${us?.configured?'done':''}"><i>3</i><div><b>验证首批真实行情</b><span>${us?.configured?'美股 Provider 已配置，可测试 NVDA / AAPL':'后端需要先配置真实 Provider Secret'}</span></div><em>${us?.configured?'可测试':'待配置'}</em></div><div class="v65-step ${active==='proxy'?'done':''}"><i>4</i><div><b>切换正式数据源</b><span>${active==='proxy'?'当前前端使用 HTTP Proxy':'当前仍使用 Mock 模拟源'}</span></div><em>${active==='proxy'?'已启用':'未启用'}</em></div><div class="v65-wizard-actions"><button data-v65-health ${configured?'':'disabled'}>检测网关</button><button data-v65-quote ${configured?'':'disabled'}>测试 NVDA</button><button data-v65-enable ${configured&&healthy?'':'disabled'}>${active==='proxy'?'已使用 HTTP Proxy':'启用 HTTP Proxy'}</button></div><div class="v65-wizard-result" data-v65-result>${configured?'可以按顺序完成检测、测试、切换。':'先在上方“行情数据源”填写你的 Worker/后端地址。'}</div><small>网页端不保存行情供应商 API Key。Key/Token 只应存在于 Worker 或其他服务端环境变量中。</small></div>`}
 function installWizard(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.v65-wizard'))return;const pc=c.querySelector('.provider-center');if(pc)pc.insertAdjacentHTML('afterend',wizardCard());else c.insertAdjacentHTML('afterbegin',wizardCard());const out=c.querySelector('[data-v65-result]'),health=c.querySelector('[data-v65-health]'),quote=c.querySelector('[data-v65-quote]'),enable=c.querySelector('[data-v65-enable]');health?.addEventListener('click',async()=>{health.disabled=true;health.textContent='检测中…';out.textContent='正在读取 /health …';try{const h=await GatewayCapabilityService.refresh();out.textContent=`连接成功 · Gateway V${h.version||'—'} · ${(h.scope||[]).join('/')||'暂无已配置市场'}`;setTimeout(()=>renderAll(),250)}catch(e){out.textContent=`检测失败 · ${e.message}`}finally{health.disabled=false;health.textContent='检测网关'}});quote?.addEventListener('click',async()=>{quote.disabled=true;quote.textContent='测试中…';out.textContent='正在请求 NVDA 真实报价…';try{const p=await getJSON('/quotes?codes=NVDA',8000),q=(p.data||p.quotes||[])[0];if(!q)throw new Error(p.errors?.[0]?.error||'empty_quote');out.textContent=`报价成功 · NVDA ${q.price} · ${q.provider||'provider'} · ${q.isMock?'模拟':'非模拟'}`}catch(e){out.textContent=`报价测试失败 · ${e.message}`}finally{quote.disabled=false;quote.textContent='测试 NVDA'}});enable?.addEventListener('click',()=>{if(!endpoint()){out.textContent='请先配置网关地址';return}MarketDataService.setProvider?.('proxy');localStorage.setItem(PROVIDER_KEY,'proxy');out.textContent='已切换到 HTTP Proxy，下一次刷新将尝试真实行情。';setTimeout(()=>renderAll(),250)})}
 function diagnosticCard(){const cap=GatewayCapabilityService?.cached?.(),health=MarketDataService?.health?.(),history=HistoryCacheService?.count?.()||0;const scriptCount=[55,56,57,58,59,60,61,62,63,64,65].filter(v=>document.querySelector(`script[src*="product-v${v}.js"]`)).length;return `<div class="v65-diag"><div class="section-head"><b>运行诊断</b><span>代码收敛阶段</span></div><div class="v65-diag-grid"><div><small>数据源</small><b>${MarketDataService?.provider==='proxy'?'HTTP Proxy':'Mock'}</b></div><div><small>网关</small><b>${cap?.ok?'已读取':'未读取'}</b></div><div><small>行情状态</small><b>${health?.status==='error'?'异常':health?.status==='loading'?'刷新中':'正常'}</b></div><div><small>历史缓存</small><b>${history} 组</b></div></div><div class="v65-consolidation"><b>前端架构</b><span>V65 已建立统一 ProductRuntime.afterRender 钩子。后续新功能将优先挂到统一运行时，不再继续增加 renderAll 覆盖链。</span><em>${scriptCount} 个产品层脚本仍在兼容运行</em></div></div>`}
 function installDiag(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.v65-diag'))return;c.insertAdjacentHTML('beforeend',diagnosticCard())}
 ProductRuntime.afterRender(installSessionStrip);
 ProductRuntime.afterRender(installWizard);
 ProductRuntime.afterRender(installDiag);
 // Make first render after this file gains V65 additions.
 setTimeout(()=>{try{ProductRuntime.run()}catch(e){}},0);
})();