// V58: resilient data UX, provider contract, custom watchlist groups and sync health.
(function(){
 const GROUP_KEY='hw-watch-groups-v1';
 const GROUP_ASSIGN_KEY='hw-watch-group-assign-v1';
 const HEALTH={status:'idle',error:null,lastSuccess:null,lastAttempt:null};
 function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}}
 function writeJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
 function groups(){const g=readJSON(GROUP_KEY,['核心','观察']);return Array.isArray(g)&&g.length?g:['核心','观察']}
 function assigns(){const a=readJSON(GROUP_ASSIGN_KEY,{});return a&&typeof a==='object'?a:{}}
 function setAssign(name,group){const a=assigns();if(group)a[name]=group;else delete a[name];writeJSON(GROUP_ASSIGN_KEY,a)}
 window.WatchGroupService={all:groups,assignments:assigns,create(name){name=String(name||'').trim().slice(0,8);if(!name)return false;const g=groups();if(!g.includes(name)){g.push(name);writeJSON(GROUP_KEY,g)}return true},remove(name){writeJSON(GROUP_KEY,groups().filter(x=>x!==name));const a=assigns();Object.keys(a).forEach(k=>{if(a[k]===name)delete a[k]});writeJSON(GROUP_ASSIGN_KEY,a)},assign:setAssign};
 // Formal provider contract used by future real-data adapters.
 window.MarketProviderContract={version:1,required:['batch'],quoteShape:['code','name','price','chg','status','provider','isMock','timestamp'],validate(adapter){return !!adapter&&typeof adapter.batch==='function'}};
 if(window.MarketDataService){
  const oldRegister=MarketDataService.register?.bind(MarketDataService);
  MarketDataService.register=function(name,adapter){if(!MarketProviderContract.validate(adapter))throw new Error('invalid_provider_adapter');return oldRegister?oldRegister(name,adapter):(this.adapters[name]=adapter)};
  const oldRefresh=MarketDataService.refresh?.bind(MarketDataService);
  MarketDataService.refresh=async function(codes){HEALTH.status='loading';HEALTH.error=null;HEALTH.lastAttempt=Date.now();document.dispatchEvent(new CustomEvent('marketdata:health',{detail:{...HEALTH}}));try{const data=oldRefresh?await oldRefresh(codes):await this.batch(codes||assets.map(a=>a.code));HEALTH.status='ok';HEALTH.lastSuccess=Date.now();return data}catch(e){HEALTH.status='error';HEALTH.error=e?.message||'refresh_failed';throw e}finally{document.dispatchEvent(new CustomEvent('marketdata:health',{detail:{...HEALTH}}))}};
  MarketDataService.health=()=>({...HEALTH,online:navigator.onLine});
 }
 function healthBanner(){const online=navigator.onLine;return `<div class="health-banner ${online?'online':'offline'}" data-health-banner><div><i></i><b>${online?'网络正常':'当前离线'}</b><span data-health-text>${online?'行情将按数据源设置刷新':'将继续显示最近一次可用数据'}</span></div><button data-health-retry ${online?'':'disabled'}>重试</button></div>`}
 function installHealth(){const c=el('content');if(!c||c.querySelector('[data-health-banner]'))return;const anchor=c.querySelector('.refresh-bar')||c.querySelector('.live-sessions')||c.firstElementChild;anchor?.insertAdjacentHTML('afterend',healthBanner());bindHealth(c)}
 function bindHealth(c){c.querySelector('[data-health-retry]')?.addEventListener('click',async e=>{if(!navigator.onLine)return;const b=e.currentTarget;b.textContent='重试中…';try{await MarketDataService.refresh()}catch(_e){}finally{b.textContent='重试'}})}
 function updateHealthUI(detail){const b=document.querySelector('[data-health-banner]');if(!b)return;const txt=b.querySelector('[data-health-text]'),title=b.querySelector('b'),dot=b.querySelector('i'),retry=b.querySelector('[data-health-retry]');const online=navigator.onLine;b.classList.toggle('offline',!online||detail.status==='error');b.classList.toggle('online',online&&detail.status!=='error');if(detail.status==='loading'){title.textContent='正在刷新';txt.textContent='正在请求行情数据…'}else if(detail.status==='error'){title.textContent='行情刷新失败';txt.textContent='继续显示最近一次可用数据';retry.disabled=!online}else if(!online){title.textContent='当前离线';txt.textContent='将继续显示最近一次可用数据';retry.disabled=true}else{title.textContent='网络正常';txt.textContent=detail.lastSuccess?`最近成功 ${new Date(detail.lastSuccess).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'行情将按数据源设置刷新';retry.disabled=false}}
 function customGroupsBar(){const selected=assets.filter(a=>favs.has(a.name)),a=assigns(),gs=groups().filter(g=>selected.some(x=>a[x.name]===g));return `<div class="custom-group-wrap"><div class="custom-group-head"><b>自定义分组</b><button data-new-group>＋ 新建</button></div><div class="custom-groups"><button data-custom-group="全部" class="active">全部</button>${gs.map(g=>`<button data-custom-group="${g}">${g}</button>`).join('')}</div></div>`}
 function assignControls(root){root.querySelectorAll('.row[data-name]').forEach(r=>{if(r.querySelector('.group-assign'))return;const name=r.dataset.name;const wrap=document.createElement('div');wrap.className='group-assign';wrap.innerHTML=`<select data-assign-name="${name}"><option value="">未分组</option>${groups().map(g=>`<option value="${g}" ${assigns()[name]===g?'selected':''}>${g}</option>`).join('')}</select>`;r.appendChild(wrap);wrap.querySelector('select').onclick=e=>e.stopPropagation();wrap.querySelector('select').onchange=e=>{e.stopPropagation();setAssign(name,e.target.value);patchCustomGroups()}})}
 function patchCustomGroups(){if(state.page!=='自选')return;const c=el('content'),list=c?.querySelector('.watch-list');if(!c||!list)return;c.querySelector('.custom-group-wrap')?.remove();list.insertAdjacentHTML('beforebegin',customGroupsBar());let active='全部';const rerender=()=>{const a=assigns();const items=assets.filter(x=>favs.has(x.name)&&(active==='全部'||a[x.name]===active));list.innerHTML=rows(items);list.querySelectorAll('.row[data-name]').forEach(r=>r.onclick=()=>openDetail(r.dataset.name));assignControls(list)};c.querySelectorAll('[data-custom-group]').forEach(b=>b.onclick=()=>{active=b.dataset.customGroup;c.querySelectorAll('[data-custom-group]').forEach(z=>z.classList.toggle('active',z===b));rerender()});c.querySelector('[data-new-group]')?.addEventListener('click',()=>{const name=prompt('输入分组名称（最多 8 个字）');if(WatchGroupService.create(name)){patchCustomGroups()}});assignControls(list)}
 function dataHealthCard(){const h=window.MarketDataService?.health?.()||{online:navigator.onLine,status:'idle'};return `<div class="data-health-card"><div><small>数据服务</small><b>${MarketDataService?.provider==='mock'?'Mock 模拟源':MarketDataService?.provider||'—'}</b></div><div><small>网络</small><b>${h.online?'在线':'离线'}</b></div><div><small>状态</small><b>${h.status==='error'?'异常':h.status==='loading'?'刷新中':'正常'}</b></div></div>`}
 function patchDataHealth(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.data-health-card'))return;const lead=c.querySelector('.data-lead');lead?.insertAdjacentHTML('afterend',dataHealthCard())}
 const baseRender=renderAll;renderAll=function(){baseRender();if(state.page==='首页')installHealth();if(state.page==='自选')patchCustomGroups();if(state.page==='数据')patchDataHealth()};
 document.addEventListener('marketdata:health',e=>updateHealthUI(e.detail));
 window.addEventListener('online',()=>updateHealthUI(MarketDataService?.health?.()||HEALTH));
 window.addEventListener('offline',()=>updateHealthUI(MarketDataService?.health?.()||HEALTH));
})();