// V61: gateway diagnostics, quote provenance, safer real-data UX and shareable asset deep links.
(function(){
 const ENDPOINT_KEY='hw-proxy-endpoint-v1';
 function endpoint(){return (localStorage.getItem(ENDPOINT_KEY)||'').trim().replace(/\/$/,'')}
 function fmtTime(ts){if(!ts)return'—';try{return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ts))}catch(e){return'—'}}
 function providerLabel(x){if(x?._fromCache)return'本地缓存';if(x?._provider==='alpha_vantage')return'Alpha Vantage';if(MarketDataService?.provider==='proxy')return'HTTP Proxy';return'Mock 模拟源'}
 function provenance(x){const ts=x?._quoteTimestamp||MarketDataService?.lastUpdated||null;const p=QuoteDelayPolicy?.policyFor?.(x)||{label:'按数据源'};const source=providerLabel(x);const mode=x?._fromCache?'缓存':MarketDataService?.provider==='mock'?'模拟':p.label;return `<div class="quote-provenance"><div><small>数据源</small><b>${source}</b></div><div><small>数据状态</small><b>${mode}</b></div><div><small>更新时间</small><b>${fmtTime(ts)}</b></div></div>`}
 function installProvenance(x){const trade=document.querySelector('.trade-detail');if(!trade||trade.querySelector('.quote-provenance'))return;const meta=trade.querySelector('.market-meta');if(meta)meta.insertAdjacentHTML('afterend',provenance(x));else trade.querySelector('.quote-block')?.insertAdjacentHTML('afterend',provenance(x))}
 async function gatewayHealth(){const base=endpoint();if(!base)throw new Error('proxy_endpoint_not_configured');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6000);try{const res=await fetch(`${base}/health`,{headers:{Accept:'application/json'},cache:'no-store',signal:controller.signal});if(!res.ok)throw new Error(`health_http_${res.status}`);return await res.json()}finally{clearTimeout(timer)}}
 function capabilityCard(){const configured=!!endpoint(),active=MarketDataService?.provider==='proxy';return `<div class="gateway-cap"><div class="section-head"><b>真实行情网关</b><span>V61 第一阶段</span></div><div class="gateway-status"><div><small>配置</small><b>${configured?'已填写地址':'未配置地址'}</b></div><div><small>当前数据源</small><b>${active?'HTTP Proxy':'Mock'}</b></div><div><small>首批范围</small><b>美股股票</b></div></div><button data-gateway-health ${configured?'':'disabled'}>检测 /health 能力</button><div class="gateway-result" data-gateway-result>${configured?'尚未检测网关能力':'请先在上方填写并保存后端地址'}</div><small>仓库已加入 Cloudflare Worker 网关模板，但模板本身不会自动部署。真实行情只有在部署后端、设置服务端 API Key 并切换到 HTTP Proxy 后才会启用。</small></div>`}
 function installCapability(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.gateway-cap'))return;const pc=c.querySelector('.provider-center');if(pc)pc.insertAdjacentHTML('afterend',capabilityCard());else c.insertAdjacentHTML('afterbegin',capabilityCard());const btn=c.querySelector('[data-gateway-health]'),out=c.querySelector('[data-gateway-result]');btn?.addEventListener('click',async()=>{btn.disabled=true;btn.textContent='检测中…';out.className='gateway-result loading';out.textContent='正在连接 /health …';try{const h=await gatewayHealth();const scope=Array.isArray(h.scope)?h.scope.join(' / '):'未声明';out.className='gateway-result ok';out.textContent=`连接正常 · ${h.provider||'unknown'} · ${scope}`}catch(e){out.className='gateway-result error';out.textContent=`检测失败 · ${e?.message||'unknown_error'}`}finally{btn.disabled=false;btn.textContent='检测 /health 能力'}})}
 function setDeepLink(x){try{const u=new URL(location.href);u.searchParams.set('asset',x.code);history.replaceState({asset:x.code},'',u)}catch(e){}}
 function clearDeepLink(){try{const u=new URL(location.href);u.searchParams.delete('asset');history.replaceState({},'',u)}catch(e){}}
 function openFromUrl(){try{const code=new URL(location.href).searchParams.get('asset');if(!code)return;const x=assets.find(a=>String(a.code).toLowerCase()===String(code).toLowerCase());if(x)setTimeout(()=>openDetail(x.name),80)}catch(e){}}
 const baseOpen=openDetail;
 openDetail=function(name){baseOpen(name);const x=assets.find(a=>a.name===name);if(!x)return;setDeepLink(x);if(x.type==='股票')installProvenance(x)};
 document.getElementById('backBtn')?.addEventListener('click',()=>setTimeout(()=>{if(el('detailSheet')?.classList.contains('hidden'))clearDeepLink()},0));
 function patchProviderReadiness(){if(state.page!=='数据')return;const c=el('content'),card=c?.querySelector('.provider-ready');if(!card||card.dataset.v61)return;card.dataset.v61='1';const rows=card.querySelectorAll(':scope > div:not(.section-head)');rows.forEach(r=>{const name=r.querySelector('b')?.textContent,em=r.querySelector('em');if(name==='股票'&&em){em.textContent='首批可接';em.classList.add('first-ready')} });const note=document.createElement('small');note.className='v61-note';note.textContent='当前网关模板先覆盖美股股票；其他市场仍保持 Mock/待接入状态。';card.appendChild(note)}
 const baseRender=renderAll;renderAll=function(){baseRender();installCapability();patchProviderReadiness()};
 document.addEventListener('DOMContentLoaded',openFromUrl);setTimeout(openFromUrl,120);
})();
