// V54 product layer: watchlist dashboard, market pulse, macro data page and richer theme details.
(function(){
 function pct(v){return `${v>=0?'+':''}${v.toFixed(2)}%`}
 function watchItems(){return assets.filter(a=>favs.has(a.name))}
 function watchDashboard(){const list=watchItems(),ups=list.filter(x=>x.chg>0).length,downs=list.filter(x=>x.chg<0).length;return `<div class="watch-hero"><div><small>我的自选</small><strong>${list.length}</strong><span>项资产</span></div><div class="watch-breadth"><b class="up">${ups} 涨</b><b class="down">${downs} 跌</b></div></div>${list.length?`<div class="watch-tools"><button data-watch-sort="chg">按涨跌幅</button><button data-watch-sort="name">按名称</button><button data-watch-sort="type">按类别</button></div><div class="list watch-list">${rows(list)}</div>`:`<div class="watch-empty"><b>还没有自选</b><span>在行情或个股详情点击 ☆，常看的资产会集中到这里。</span><button data-go-market>去行情添加</button></div>`}`}
 function bindRows(root){root.querySelectorAll('.row[data-name]').forEach(r=>r.onclick=()=>openDetail(r.dataset.name))}
 function enhanceWatch(){if(state.page!=='自选')return;const c=el('content');if(!c)return;c.innerHTML=watchDashboard();c.querySelector('[data-go-market]')?.addEventListener('click',()=>{state.page='行情';renderAll()});c.querySelectorAll('[data-watch-sort]').forEach(b=>b.onclick=()=>{const mode=b.dataset.watchSort,a=watchItems();if(mode==='chg')a.sort((x,y)=>y.chg-x.chg);if(mode==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'zh-CN'));if(mode==='type')a.sort((x,y)=>x.type.localeCompare(y.type,'zh-CN'));const list=c.querySelector('.watch-list');if(list){list.innerHTML=rows(a);bindRows(list)}});bindRows(c)}
 function pulse(){const stocks=assets.filter(x=>x.type==='股票'),up=stocks.filter(x=>x.chg>0).length,down=stocks.filter(x=>x.chg<0).length,avg=stocks.reduce((s,x)=>s+x.chg,0)/(stocks.length||1);return `<div class="market-pulse"><div><small>全球代表股</small><b>${stocks.length}</b></div><div><small>上涨 / 下跌</small><b><i class="up">${up}</i> / <i class="down">${down}</i></b></div><div><small>平均涨跌</small><b class="${avg>=0?'up':'down'}">${pct(avg)}</b></div></div>`}
 function asset(name){return assets.find(x=>x.name===name)}
 function quoteCard(name,label){const x=asset(name);if(!x)return'';return `<button class="data-quote" data-name="${x.name}"><small>${label||x.name}</small><b>${x.price}</b><span class="${x.chg>=0?'up':'down'}">${pct(x.chg)}</span></button>`}
 function yieldCurve(){const ys=[asset('美国2年期国债'),asset('美国10年期国债'),asset('美国30年期国债')].filter(Boolean);return `<div class="yield-card"><div class="section-head"><b>美债收益率曲线</b><span>模拟/静态行情</span></div><div class="yield-curve">${ys.map((x,i)=>`<div><i style="height:${44+i*15}px"></i><b>${x.price}</b><span>${i===0?'2Y':i===1?'10Y':'30Y'}</span></div>`).join('')}</div></div>`}
 function sessions(){return `<div class="session-grid"><div><i class="dot open"></i><b>亚洲</b><span>日/韩/中国</span></div><div><i class="dot wait"></i><b>欧洲</b><span>未开盘</span></div><div><i class="dot closed"></i><b>美国</b><span>休市</span></div></div>`}
 function dataDashboard(){return `<div class="data-lead"><small>宏观与跨资产</small><b>今天市场在交易什么？</b><span>先建立数据页结构，真实宏观数据将在统一数据层接入。</span></div>${sessions()}<div class="section"><div class="section-head"><b>核心资产</b><span>跨市场观察</span></div><div class="data-grid">${quoteCard('美元指数','美元指数')}${quoteCard('黄金','黄金')}${quoteCard('WTI原油','WTI原油')}${quoteCard('铜','LME铜')}${quoteCard('美国10年期国债','美国10Y')}${quoteCard('纳斯达克100','纳指100')}</div></div>${yieldCurve()}<div class="macro-card"><div class="section-head"><b>宏观事件</b><span>结构预览</span></div><div class="macro-row"><span>09:30</span><div><b>中国通胀数据</b><small>关注消费与工业价格趋势</small></div><em>待公布</em></div><div class="macro-row"><span>20:30</span><div><b>美国就业数据</b><small>可能影响美元与美债收益率</small></div><em>高关注</em></div><div class="macro-row"><span>22:00</span><div><b>央行官员讲话</b><small>关注利率路径表述</small></div><em>关注</em></div><div class="mock-inline">事件内容为产品结构示例，并非当前真实经济日历。</div></div>`}
 function enhanceData(){if(state.page!=='数据')return;const c=el('content');if(!c)return;c.innerHTML=dataDashboard();c.querySelectorAll('.data-quote[data-name]').forEach(b=>b.onclick=()=>openDetail(b.dataset.name))}
 function marketListForTheme(){const key=state.region==='全球'?'美股':state.region;return state.type==='概念'?(conceptData[key]||[]):(sectorData[key]||[])}
 function repsForTheme(name){const region=state.region==='全球'?null:state.region;let a=assets.filter(x=>x.type==='股票'&&(!region||x.region===region));const keys=name.replace(/AI|设备|服务|概念/g,'').split(/[\s/]+/).filter(Boolean);let matched=a.filter(x=>keys.some(k=>(x.group||'').includes(k)||(x.name||'').includes(k)));if(matched.length<3)matched=[...a].sort((x,y)=>Math.abs(y.chg)-Math.abs(x.chg));return matched.slice(0,5)}
 function themeTrend(chg){const up=chg>=0,base=up?[110,104,96,100,82,74,68,55,61,45,38,31]:[38,45,41,57,53,69,77,72,91,99,108,114];return base.map((y,i)=>`${i*32.7},${y}`).join(' ')}
 if(typeof openThemeDetail==='function')openThemeDetail=function(name,chg){const region=state.region==='全球'?'全球':state.region,kind=state.type==='概念'?'概念':'板块',list=marketListForTheme(),ups=list.filter(x=>x.chg>0).length,downs=list.filter(x=>x.chg<0).length,reps=repsForTheme(name);el('detailTitle').textContent=name;el('detailCode').textContent=`${region}${kind} · 模拟行情`;const card=el('detailSheet').querySelector('.detail-card');card.innerHTML=`<div class="theme-detail"><div class="theme-head"><div><small>${region}${kind}</small><strong class="${chg>=0?'up':'down'}">${pct(chg)}</strong></div><span>${chg>=0?'领涨':'走弱'}</span></div><div class="theme-metrics"><div><small>上涨</small><b class="up">${ups}</b></div><div><small>下跌</small><b class="down">${downs}</b></div><div><small>强度</small><b>${Math.abs(chg)>=2?'强':'中性'}</b></div><div><small>样本</small><b>${list.length}</b></div></div><div class="theme-chart"><svg viewBox="0 0 360 140" preserveAspectRatio="none"><line x1="0" y1="70" x2="360" y2="70"/><polyline class="${chg>=0?'up':'down'}" points="${themeTrend(chg)}" fill="none" stroke="currentColor" stroke-width="3"/></svg><span>模拟板块走势 · 后续接入真实成分股聚合</span></div><div class="section-head inner"><b>代表个股</b><span>${reps.length} 项</span></div><div class="list mini-list">${rows(reps)}</div></div>`;document.getElementById('favBtn')?.remove();el('detailSheet').classList.remove('hidden');bindRows(card)}
 const baseRender=renderAll;renderAll=function(){baseRender();if(state.page==='自选')enhanceWatch();if(state.page==='数据')enhanceData();if(state.page==='首页'){const c=el('content'),hero=c?.querySelector('.hero');if(hero&&!c.querySelector('.market-pulse'))hero.insertAdjacentHTML('afterend',pulse())}}
})();