// V57: price-alert rules, watchlist smart groups, provider refresh infrastructure and holiday hooks.
(function(){
 const RULE_KEY='hw-alert-rules-v2', LEGACY_KEY='hw-price-reminders-v1';
 const REFRESH_MS=30000;
 function readRules(){try{const r=JSON.parse(localStorage.getItem(RULE_KEY)||'{}');return r&&typeof r==='object'?r:{}}catch(e){return {}}}
 function writeRules(r){localStorage.setItem(RULE_KEY,JSON.stringify(r))}
 function migrateLegacy(){let rules=readRules();if(Object.keys(rules).length)return;try{const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]');old.forEach(name=>{rules[name]={enabled:true,mode:'pct',value:3,createdAt:Date.now()}});writeRules(rules)}catch(e){}}
 migrateLegacy();
 window.PriceAlertService={
  all(){return readRules()},
  get(name){return readRules()[name]||null},
  set(name,rule){const r=readRules();r[name]={enabled:true,mode:'pct',value:3,createdAt:Date.now(),...rule};writeRules(r);return r[name]},
  remove(name){const r=readRules();delete r[name];writeRules(r)},
  clear(){writeRules({})}
 };
 // Holiday calendar hook. Empty by design until an official exchange calendar feed is connected.
 window.ExchangeCalendar={holidays:{'A股':[],'港股':[],'美股':[],'日本':[],'韩国':[],'欧洲':[]},isHoliday(kind,date){const d=date||new Date();const key=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');return (this.holidays[kind]||[]).includes(key)},load(kind,dates){this.holidays[kind]=Array.isArray(dates)?dates:[]}};
 // Extend the V56 provider skeleton into an adapter-based refresh layer.
 if(window.MarketDataService){
  MarketDataService.adapters=MarketDataService.adapters||{mock:{async batch(codes){return codes.map(c=>assets.find(a=>a.code===c)).filter(Boolean).map(x=>({...x,provider:'mock',isMock:true}))}}};
  MarketDataService.register=function(name,adapter){if(name&&adapter)this.adapters[name]=adapter};
  MarketDataService.refresh=async function(codes){const adapter=this.adapters[this.provider]||this.adapters.mock;const data=await adapter.batch(codes||assets.map(a=>a.code));this.lastUpdated=Date.now();document.dispatchEvent(new CustomEvent('marketdata:updated',{detail:{provider:this.provider,count:data.length,at:this.lastUpdated}}));return data};
 }
 function fmtTime(ts){return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ts||Date.now()))}
 function refreshBar(){const provider=window.MarketDataService?.provider==='mock'?'Mock 模拟源':window.MarketDataService?.provider||'—';return `<div class="refresh-bar"><div><i class="refresh-dot"></i><span>行情层：${provider}</span></div><button data-refresh-now>刷新</button><small data-refresh-time>最近刷新 ${fmtTime()}</small></div>`}
 function installRefreshBar(){if(state.page!=='首页')return;const c=el('content');if(!c||c.querySelector('.refresh-bar'))return;const s=c.querySelector('.live-sessions')||c.firstElementChild;s?.insertAdjacentHTML('afterend',refreshBar());c.querySelector('[data-refresh-now]')?.addEventListener('click',async e=>{const b=e.currentTarget;b.textContent='刷新中…';try{await MarketDataService.refresh();const t=c.querySelector('[data-refresh-time]');if(t)t.textContent=`最近刷新 ${fmtTime(MarketDataService.lastUpdated)}`}finally{b.textContent='刷新'}})}
 function ruleLabel(rule){if(!rule)return'未设置';if(rule.mode==='above')return`高于 ${rule.value}`;if(rule.mode==='below')return`低于 ${rule.value}`;return`涨跌 ±${rule.value}%`}
 function alertEditor(x){const r=PriceAlertService.get(x.name)||{mode:'pct',value:3};return `<div class="alert-editor"><div class="section-head"><b>价格提醒</b><span>本机规则</span></div><div class="alert-mode">${[['pct','涨跌幅'],['above','价格高于'],['below','价格低于']].map(([k,l])=>`<button data-alert-mode="${k}" class="${r.mode===k?'active':''}">${l}</button>`).join('')}</div><div class="alert-value"><span>${r.mode==='pct'?'阈值':'目标价'}</span><button data-alert-minus>−</button><strong data-alert-value>${r.value}</strong><button data-alert-plus>＋</button><em>${r.mode==='pct'?'%':''}</em></div><div class="alert-note">当前仅保存提醒条件，不会发送系统推送；真实推送需要后端行情监控与通知服务。</div></div>`}
 function bindAlertEditor(x){const root=document.querySelector('.alert-editor');if(!root)return;let r=PriceAlertService.get(x.name)||{enabled:true,mode:'pct',value:3};const save=()=>{PriceAlertService.set(x.name,r);const btn=document.querySelector('[data-action="alert"]');if(btn){btn.textContent='✓ 已提醒';btn.classList.add('reminder-on')}};const renderValue=()=>{const v=root.querySelector('[data-alert-value]'),em=root.querySelector('.alert-value em'),label=root.querySelector('.alert-value>span');if(v)v.textContent=r.value;if(em)em.textContent=r.mode==='pct'?'%':'';if(label)label.textContent=r.mode==='pct'?'阈值':'目标价'};root.querySelectorAll('[data-alert-mode]').forEach(b=>b.onclick=()=>{r.mode=b.dataset.alertMode;if(r.mode!=='pct'&&r.value<=10){const p=parseFloat(String(x.price).replace(/,/g,''));r.value=Number.isFinite(p)?+p.toFixed(2):100}root.querySelectorAll('[data-alert-mode]').forEach(z=>z.classList.toggle('active',z===b));renderValue();save()});root.querySelector('[data-alert-minus]')?.addEventListener('click',()=>{const step=r.mode==='pct'?1:Math.max(.01,Math.round(r.value*.01*100)/100);r.value=Math.max(r.mode==='pct'?1:.01,+(r.value-step).toFixed(2));renderValue();save()});root.querySelector('[data-alert-plus]')?.addEventListener('click',()=>{const step=r.mode==='pct'?1:Math.max(.01,Math.round(r.value*.01*100)/100);r.value=+(r.value+step).toFixed(2);renderValue();save()})}
 const baseOpen=openDetail;
 openDetail=function(name){baseOpen(name);const x=assets.find(a=>a.name===name);if(!x||x.type!=='股票')return;const trade=document.querySelector('.trade-detail');if(!trade)return;trade.querySelector('.alert-editor')?.remove();const actions=trade.querySelector('.detail-actions');if(actions)actions.insertAdjacentHTML('beforebegin',alertEditor(x));bindAlertEditor(x);const btn=trade.querySelector('[data-action="alert"]');if(btn){const has=!!PriceAlertService.get(name);btn.textContent=has?'✓ 已提醒':'提醒';btn.classList.toggle('reminder-on',has);btn.onclick=()=>{if(PriceAlertService.get(name)){PriceAlertService.remove(name);btn.textContent='提醒';btn.classList.remove('reminder-on');trade.querySelector('.alert-editor')?.remove();actions?.insertAdjacentHTML('beforebegin',alertEditor(x));bindAlertEditor(x)}else{PriceAlertService.set(name,{mode:'pct',value:3});btn.textContent='✓ 已提醒';btn.classList.add('reminder-on')}}}}
 function watchGroups(){const selected=assets.filter(a=>favs.has(a.name));const defs=['全部','股票','指数','商品','外汇','债券'];return defs.filter(k=>k==='全部'||selected.some(x=>x.type===k))}
 function patchWatchGroups(){if(state.page!=='自选')return;const c=el('content');if(!c||c.querySelector('.watch-groups'))return;const list=c.querySelector('.watch-list');if(!list)return;let active='全部';const groups=watchGroups();list.insertAdjacentHTML('beforebegin',`<div class="watch-groups">${groups.map((g,i)=>`<button data-watch-group="${g}" class="${i===0?'active':''}">${g}</button>`).join('')}</div>`);c.querySelectorAll('[data-watch-group]').forEach(b=>b.onclick=()=>{active=b.dataset.watchGroup;c.querySelectorAll('[data-watch-group]').forEach(z=>z.classList.toggle('active',z===b));const a=assets.filter(x=>favs.has(x.name)&&(active==='全部'||x.type===active));list.innerHTML=rows(a);list.querySelectorAll('.row[data-name]').forEach(r=>r.onclick=()=>openDetail(r.dataset.name))})}
 function patchReminderManager(){if(state.page!=='自选')return;const c=el('content'),card=c?.querySelector('.reminder-card');if(!card)return;const rules=PriceAlertService.all(),items=assets.filter(x=>rules[x.name]);card.innerHTML=`<div class="section-head"><b>价格提醒</b><span>${items.length} 项</span></div>${items.length?`<div class="rule-list">${items.map(x=>`<div><button data-rule-open="${x.name}"><b>${x.name}</b><span>${x.code} · ${ruleLabel(rules[x.name])}</span></button><button data-rule-remove="${x.name}">关闭</button></div>`).join('')}</div><button class="clear-reminders" data-rule-clear>清空全部提醒</button>`:`<div class="reminder-empty">还没有价格提醒。进入个股详情可设置涨跌幅或目标价条件。</div>`}<div class="provider-line"><span>行情数据层</span><b>${MarketDataService.provider==='mock'?'Mock 模拟源':MarketDataService.provider}</b></div>`;card.querySelectorAll('[data-rule-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.ruleOpen));card.querySelectorAll('[data-rule-remove]').forEach(b=>b.onclick=()=>{PriceAlertService.remove(b.dataset.ruleRemove);renderAll()});card.querySelector('[data-rule-clear]')?.addEventListener('click',()=>{PriceAlertService.clear();renderAll()})}
 const baseRender=renderAll;renderAll=function(){baseRender();installRefreshBar();patchWatchGroups();patchReminderManager()};
 document.addEventListener('marketdata:updated',e=>{const t=document.querySelector('[data-refresh-time]');if(t)t.textContent=`最近刷新 ${fmtTime(e.detail.at)}`});
 setInterval(()=>{if(document.visibilityState==='visible'&&state.page==='首页'&&window.MarketDataService)MarketDataService.refresh().catch(()=>{})},REFRESH_MS);
})();