// V62: market routing, gateway capability map, history API client and real-K-line preview.
(function(){
 const ENDPOINT_KEY='hw-proxy-endpoint-v1', CAP_KEY='hw-gateway-cap-v62';
 function endpoint(){return (localStorage.getItem(ENDPOINT_KEY)||'').trim().replace(/\/$/,'')}
 function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}}
 function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function marketOf(x){const code=String(x?.code||x||'').toUpperCase(),tag=String(x?.tag||'');if(tag==='A股'||/^\d{6}$/.test(code))return'CN';if(tag==='港股'||/^\d{4}\.HK$/.test(code))return'HK';if(/\.T$/.test(code))return'JP';if(/\.KS$/.test(code))return'KR';if(/\.(DE|AS|PA)$/.test(code))return'EU';if(/^[A-Z][A-Z0-9.-]{0,9}$/.test(code))return'US';return'OTHER'}
 window.MarketRouteService={marketOf,label(m){return({CN:'A股',HK:'港股',US:'美股',JP:'日本',KR:'韩国',EU:'欧洲',OTHER:'其他'})[m]||m},providerHint(m){return({US:'Alpha Vantage',CN:'CN Provider',HK:'HK Provider'})[m]||'待接入'}};
 async function getJSON(path,timeout=8000){const base=endpoint();if(!base)throw new Error('proxy_endpoint_not_configured');const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const res=await fetch(base+path,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});const payload=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(payload?.error||`http_${res.status}`);e.status=res.status;e.payload=payload;throw e}return payload}finally{clearTimeout(timer)}}
 window.GatewayCapabilityService={
  async refresh(){const h=await getJSON('/health',6000);writeJSON(CAP_KEY,{...h,savedAt:Date.now()});document.dispatchEvent(new CustomEvent('gateway:capabilities',{detail:h}));return h},
  cached(){return readJSON(CAP_KEY,null)},
  market(m){return this.cached()?.providers?.[m]||null},
  quoteReady(x){const p=this.market(marketOf(x));return !!p?.configured&&!!p?.quotes},
  historyReady(x,period='1d'){const p=this.market(marketOf(x));return !!p?.configured&&Array.isArray(p?.history)&&p.history.includes(period)}
 };
 window.MarketHistoryService={
  async load(code,period='1d'){const p=await getJSON(`/history?code=${encodeURIComponent(code)}&period=${encodeURIComponent(period)}`,10000);if(!Array.isArray(p.points))throw new Error('invalid_history_payload');return p}
 };
 function capBadge(m,p){if(!p)return'<em class="cap pending">未知</em>';if(p.configured&&p.quotes)return'<em class="cap ready">报价已配置</em>';return'<em class="cap pending">待配置</em>'}
 function capabilityMatrix(){const c=GatewayCapabilityService.cached(),markets=['US','CN','HK','JP','KR','EU'];return `<div class="route-matrix"><div class="section-head"><b>市场路由能力</b><span>${c?.version?'Gateway V'+esc(c.version):'尚未读取 /health'}</span></div>${markets.map(m=>{const p=c?.providers?.[m];return `<div class="route-row"><b>${MarketRouteService.label(m)}</b><span>${p?.provider||MarketRouteService.providerHint(m)}</span><span>${p?.history?.length?'日K':''}</span>${capBadge(m,p)}</div>`}).join('')}<button data-cap-refresh ${endpoint()?'':'disabled'}>重新读取网关能力</button><small>“已配置”只表示后端 Provider 已启用；是否实时、是否延迟仍以具体数据授权为准。</small></div>`}
 function installMatrix(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.route-matrix'))return;const g=c.querySelector('.gateway-cap');if(g)g.insertAdjacentHTML('afterend',capabilityMatrix());else c.insertAdjacentHTML('beforeend',capabilityMatrix());const b=c.querySelector('[data-cap-refresh]');b?.addEventListener('click',async()=>{b.disabled=true;b.textContent='读取中…';try{await GatewayCapabilityService.refresh();renderAll()}catch(e){b.textContent=`读取失败 · ${e.message}`;setTimeout(()=>{b.textContent='重新读取网关能力';b.disabled=false},1600);return}b.disabled=false})}
 function pointsPath(points,w=360,h=130){if(!points?.length)return'';const vals=points.map(p=>Number(p.c)).filter(Number.isFinite);if(!vals.length)return'';let lo=Math.min(...vals),hi=Math.max(...vals);if(hi===lo){hi+=1;lo-=1}return points.map((p,i)=>{const x=points.length===1?w/2:i*w/(points.length-1),y=h-(Number(p.c)-lo)/(hi-lo)*h;return`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}
 function historyPanel(x){const market=marketOf(x),ready=MarketDataService?.provider==='proxy'&&GatewayCapabilityService.historyReady(x,'1d');return `<div class="real-history"><div class="section-head"><b>真实日K通道</b><span>${MarketRouteService.label(market)} · /history</span></div><div class="history-state" data-history-state>${MarketDataService?.provider==='proxy'?(ready?'网关已声明支持，可加载真实日K':'当前网关未声明该市场日K能力'):'当前使用 Mock；切换 HTTP Proxy 后可检测真实日K'}</div><button data-load-history ${ready?'':'disabled'}>加载最近日K</button><div data-history-result></div></div>`}
 function renderHistory(root,payload){const pts=(payload.points||[]).slice(-60),last=pts[pts.length-1],first=pts[0],chg=first&&last&&first.c?((last.c-first.c)/first.c*100):0,path=pointsPath(pts);root.innerHTML=`<div class="history-summary"><div><small>数据源</small><b>${esc(payload.provider||'—')}</b></div><div><small>样本</small><b>${pts.length} 日</b></div><div><small>区间变化</small><b class="${chg>=0?'up':'down'}">${chg>=0?'+':''}${chg.toFixed(2)}%</b></div></div><svg class="history-chart ${chg>=0?'up':'down'}" viewBox="0 0 360 140" preserveAspectRatio="none"><path d="${path}" fill="none" stroke="currentColor" stroke-width="3"/></svg><div class="history-foot">${last?`最近收盘 ${last.c} · ${new Date(last.ts).toLocaleDateString('zh-CN')}`:'暂无数据'}</div>`}
 function installHistory(x){if(x?.type!=='股票')return;const trade=document.querySelector('.trade-detail');if(!trade||trade.querySelector('.real-history'))return;const related=trade.querySelector('.related-stocks')||trade.querySelector('.detail-actions');if(related)related.insertAdjacentHTML('beforebegin',historyPanel(x));else trade.insertAdjacentHTML('beforeend',historyPanel(x));const btn=trade.querySelector('[data-load-history]'),stateBox=trade.querySelector('[data-history-state]'),out=trade.querySelector('[data-history-result]');btn?.addEventListener('click',async()=>{btn.disabled=true;btn.textContent='加载中…';stateBox.textContent='正在请求真实历史行情…';try{const p=await MarketHistoryService.load(x.code,'1d');stateBox.textContent=`加载成功 · ${p.provider||'provider'} · ${p.points.length} 条`;renderHistory(out,p)}catch(e){stateBox.textContent=`加载失败 · ${e.message}`;out.innerHTML='<div class="history-error">继续保留当前模拟图表，不会用失败结果覆盖页面。</div>'}finally{btn.disabled=false;btn.textContent='重新加载日K'}})}
 const baseOpen=openDetail;openDetail=function(name){baseOpen(name);const x=assets.find(a=>a.name===name);if(x)installHistory(x)};
 const baseRender=renderAll;renderAll=function(){baseRender();installMatrix()};
 document.addEventListener('gateway:capabilities',()=>{if(state.page==='数据')renderAll()});
 // If Proxy is already configured, refresh capabilities once per session without blocking the UI.
 if(endpoint()&&MarketDataService?.provider==='proxy'&&!GatewayCapabilityService.cached())setTimeout(()=>GatewayCapabilityService.refresh().catch(()=>{}),300);
})();
