// V67: unified detail hook, live quote state and compatibility cleanup.
(function(){
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function assetByName(name){return assets.find(a=>a.name===name)}
 if(window.ProductRuntime&&!ProductRuntime.afterDetail){
  const hooks=[];ProductRuntime.afterDetail=function(fn){if(typeof fn==='function'&&!hooks.includes(fn))hooks.push(fn)};ProductRuntime.runDetail=function(x){hooks.slice().forEach(fn=>{try{fn(x)}catch(e){console.warn('detail hook failed',e)}})};
  const currentOpen=openDetail;openDetail=function(name){currentOpen(name);const x=assetByName(name);if(x)ProductRuntime.runDetail(x)};
 }
 function fmt(ts){return ts?new Date(ts).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—'}
 function quoteState(x){const provider=MarketDataService?.provider||'mock',cached=!!x._fromCache;return {provider,label:cached?'缓存行情':provider==='proxy'?'HTTP Proxy':'Mock 模拟',real:provider==='proxy'&&!cached,at:x.timestamp||MarketDataService?.lastUpdated||null}}
 function quoteBar(x){const q=quoteState(x);return `<div class="v67-live ${q.real?'real':'mock'}"><div><i></i><span>行情来源</span><b data-v67-source>${esc(q.label)}</b></div><div><span>更新时间</span><b data-v67-time>${fmt(q.at)}</b></div><button data-v67-refresh>${q.real?'刷新报价':'刷新'}</button><small data-v67-msg>${q.real?'使用已配置网关；是否实时/延迟以 Provider 授权为准。':'当前不是已确认的实时行情。'}</small></div>`}
 function installQuoteBar(x){if(x?.type!=='股票')return;const trade=document.querySelector('.trade-detail');if(!trade)return;trade.querySelector('.v67-live')?.remove();const anchor=trade.querySelector('.quote-provenance')||trade.querySelector('.market-meta')||trade.querySelector('.quote-block');anchor?.insertAdjacentHTML('afterend',quoteBar(x));const box=trade.querySelector('.v67-live'),btn=box?.querySelector('[data-v67-refresh]'),msg=box?.querySelector('[data-v67-msg]');btn?.addEventListener('click',async()=>{btn.disabled=true;btn.textContent='刷新中…';msg.textContent='正在请求最新可用报价…';try{const data=await MarketDataService.refresh([x.code]),q=data?.find?.(z=>z.code===x.code)||data?.[0];if(q){Object.assign(x,q);box.querySelector('[data-v67-source]').textContent=q._fromCache?'缓存行情':q.isMock?'Mock 模拟':q.provider||'Provider';box.querySelector('[data-v67-time]').textContent=fmt(q.timestamp||Date.now());msg.textContent=q._fromCache?'网关失败，当前显示最近一次缓存。':'刷新成功；实时/延迟属性以数据源授权为准。'}else msg.textContent='没有返回该资产报价。'}catch(e){msg.textContent=`刷新失败 · ${e?.message||'unknown_error'}`}finally{btn.disabled=false;btn.textContent='刷新报价'}})}
 function cleanupDetail(x){if(x?.type!=='股票')return;const trade=document.querySelector('.trade-detail');if(!trade)return;const sessions=[...trade.querySelectorAll('.v63-session')];sessions.slice(1).forEach(n=>n.remove());const histories=[...trade.querySelectorAll('.v63-history')];histories.slice(1).forEach(n=>n.remove());}
 function architecture(){if(state.page!=='数据')return;const diag=el('content')?.querySelector('.v65-diag');if(!diag||diag.querySelector('.v67-arch'))return;diag.insertAdjacentHTML('beforeend','<div class="v67-arch"><b>V67 详情运行时</b><span>已建立 ProductRuntime.afterDetail：后续个股扩展统一从详情钩子进入，不再新增 openDetail 包装链。V55–V64 暂保留兼容，逐步迁移后再删除。</span></div>')}
 if(window.ProductRuntime){ProductRuntime.afterDetail?.(cleanupDetail);ProductRuntime.afterDetail?.(installQuoteBar);ProductRuntime.afterRender(architecture);setTimeout(()=>ProductRuntime.run(),0)}
})();