// V63: unified market sessions + holiday hook + multi-period real history UX.
(function(){
 function parts(tz,date=new Date()){const f=new Intl.DateTimeFormat('en-US',{timeZone:tz,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const p=Object.fromEntries(f.formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {...p,mins:+p.hour*60+(+p.minute),key:`${p.year}-${p.month}-${p.day}`}}
 function kindOf(x){const m=window.MarketRouteService?.marketOf?.(x)||'OTHER';return({CN:'A股',HK:'港股',US:'美股',JP:'日本',KR:'韩国',EU:'欧洲'})[m]||'其他'}
 const CFG={
  'A股':{tz:'Asia/Shanghai',sessions:[[570,690],[780,900]],label:'09:30–11:30 / 13:00–15:00'},
  '港股':{tz:'Asia/Hong_Kong',sessions:[[570,720],[780,960]],label:'09:30–12:00 / 13:00–16:00'},
  '美股':{tz:'America/New_York',sessions:[[570,960]],label:'09:30–16:00'},
  '日本':{tz:'Asia/Tokyo',sessions:[[540,690],[750,900]],label:'09:00–11:30 / 12:30–15:00'},
  '韩国':{tz:'Asia/Seoul',sessions:[[540,930]],label:'09:00–15:30'},
  '欧洲':{tz:'Europe/Berlin',sessions:[[540,1050]],label:'09:00–17:30'}
 };
 window.MarketSessionService={
  kindOf,config:CFG,
  status(x,date=new Date()){const kind=kindOf(x),cfg=CFG[kind];if(!cfg)return{kind,status:'未知',open:false,note:'暂无交易时段配置'};const p=parts(cfg.tz,date),weekend=['Sat','Sun'].includes(p.weekday),holiday=(window.ExchangeCalendar?.holidays?.[kind]||[]).includes(p.key);if(weekend)return{kind,status:'休市',open:false,note:'周末',local:p.key,session:cfg.label};if(holiday)return{kind,status:'休市',open:false,note:'交易所节假日',local:p.key,session:cfg.label};const open=cfg.sessions.some(([a,b])=>p.mins>=a&&p.mins<b);return{kind,status:open?'交易中':'休市',open,note:open?'常规交易时段':'常规时段外',local:p.key,session:cfg.label}}
 };
 function sessionCard(x){const s=MarketSessionService.status(x);const cal=ExchangeCalendar?.info?.(s.kind),calendarReady=!!cal?.count;return `<div class="v63-session"><div><small>市场状态</small><b class="${s.open?'open':'closed'}"><i></i>${s.status}</b></div><div><small>常规时段</small><b>${s.session||'—'}</b></div><div><small>节假日</small><b>${calendarReady?'已接日历':'未接日历'}</b></div><span>${s.note} · 自动判断为估算状态${calendarReady?'':'，尚未纳入官方节假日'}</span></div>`}
 function installSession(x){if(x?.type!=='股票')return;const trade=document.querySelector('.trade-detail');if(!trade||trade.querySelector('.v63-session'))return;const prov=trade.querySelector('.quote-provenance')||trade.querySelector('.market-meta')||trade.querySelector('.quote-block');prov?.insertAdjacentHTML('afterend',sessionCard(x))}
 function historyReady(x,p){return MarketDataService?.provider==='proxy'&&!!GatewayCapabilityService?.historyReady?.(x,p)}
 function historyBox(x){const periods=[['1d','日K'],['1w','周K'],['1m','月K']],available=periods.filter(([p])=>historyReady(x,p));return `<div class="v63-history"><div class="section-head"><b>真实历史行情</b><span>/history</span></div><div class="v63-history-tabs">${periods.map(([p,l],i)=>`<button data-v63-period="${p}" class="${i===0?'active':''}" ${historyReady(x,p)?'':'disabled'}>${l}</button>`).join('')}</div><div class="v63-history-state" data-v63-history-state>${MarketDataService?.provider==='proxy'?(available.length?`网关支持：${available.map(x=>x[1]).join(' / ')}`:'当前网关未声明历史行情能力'):'当前为 Mock；切换 HTTP Proxy 后自动检测能力'}</div><button class="v63-history-load" data-v63-history-load ${available.length?'':'disabled'}>加载日K</button><div data-v63-history-result></div></div>`}
 function path(points,w=360,h=135){const a=(points||[]).filter(p=>Number.isFinite(+p.c));if(!a.length)return'';let lo=Math.min(...a.map(p=>+p.c)),hi=Math.max(...a.map(p=>+p.c));if(lo===hi){lo-=1;hi+=1}return a.map((p,i)=>`${i?'L':'M'}${(i*w/Math.max(1,a.length-1)).toFixed(1)},${(h-(+p.c-lo)/(hi-lo)*h).toFixed(1)}`).join(' ')}
 function renderHistory(out,payload){const pts=(payload.points||[]).slice(-80),first=pts[0],last=pts[pts.length-1],chg=first&&last&&+first.c?((+last.c-+first.c)/+first.c*100):0;out.innerHTML=`<div class="v63-hsummary"><div><small>数据源</small><b>${payload.provider||'—'}</b></div><div><small>数据点</small><b>${pts.length}</b></div><div><small>区间</small><b class="${chg>=0?'up':'down'}">${chg>=0?'+':''}${chg.toFixed(2)}%</b></div></div><svg class="v63-hchart ${chg>=0?'up':'down'}" viewBox="0 0 360 145" preserveAspectRatio="none"><path d="${path(pts)}" fill="none" stroke="currentColor" stroke-width="3"/></svg><div class="v63-hfoot">${last?`最近收盘 ${last.c} · ${new Date(last.ts).toLocaleDateString('zh-CN')}`:'暂无数据'}</div>`}
 function installHistory(x){if(x?.type!=='股票')return;const trade=document.querySelector('.trade-detail');if(!trade)return;trade.querySelector('.real-history')?.remove();trade.querySelector('.v63-history')?.remove();const anchor=trade.querySelector('.related-stocks')||trade.querySelector('.detail-actions');if(anchor)anchor.insertAdjacentHTML('beforebegin',historyBox(x));else trade.insertAdjacentHTML('beforeend',historyBox(x));const box=trade.querySelector('.v63-history'),stateBox=box.querySelector('[data-v63-history-state]'),load=box.querySelector('[data-v63-history-load]'),out=box.querySelector('[data-v63-history-result]');let period=box.querySelector('[data-v63-period]:not([disabled])')?.dataset.v63Period||'1d';box.querySelectorAll('[data-v63-period]').forEach(b=>b.onclick=()=>{period=b.dataset.v63Period;box.querySelectorAll('[data-v63-period]').forEach(z=>z.classList.toggle('active',z===b));load.textContent=`加载${b.textContent}`;out.innerHTML=''});load?.addEventListener('click',async()=>{load.disabled=true;load.textContent='加载中…';stateBox.textContent='正在请求真实历史行情…';try{const p=await MarketHistoryService.load(x.code,period);stateBox.textContent=`加载成功 · ${p.provider||'provider'} · ${p.points.length} 条`;renderHistory(out,p)}catch(e){stateBox.textContent=`加载失败 · ${e.message}`;out.innerHTML='<div class="v63-herror">失败不会覆盖当前模拟图表。</div>'}finally{load.disabled=false;const tab=box.querySelector(`[data-v63-period="${period}"]`);load.textContent=`重新加载${tab?.textContent||'历史行情'}`}})}
 function sessionDataCard(){const names=['A股','港股','美股','日本','韩国','欧洲'];return `<div class="session-engine"><div class="section-head"><b>交易时段引擎</b><span>V63</span></div>${names.map(k=>{const cfg=CFG[k],count=ExchangeCalendar?.info?.(k)?.count||0;return `<div><b>${k}</b><span>${cfg.label}</span><em class="${count?'ready':'pending'}">${count?'含节假日':'常规时段'}</em></div>`}).join('')}<small>状态按各市场时区计算；未加载官方交易所日历时，仅按工作日与常规时段估算。</small></div>`}
 function installDataCard(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.session-engine'))return;const m=c.querySelector('.route-matrix');if(m)m.insertAdjacentHTML('afterend',sessionDataCard());else c.insertAdjacentHTML('beforeend',sessionDataCard())}
 const baseOpen=openDetail;openDetail=function(name){baseOpen(name);const x=assets.find(a=>a.name===name);if(x){installSession(x);installHistory(x)}};
 const baseRender=renderAll;renderAll=function(){baseRender();installDataCard()};
})();
