// V56: smart search, automatic session estimates, reminder manager, and a unified data-provider skeleton.
(function(){
 const REMINDER_KEY='hw-price-reminders-v1';
 const PROVIDER_KEY='hw-data-provider-v1';
 window.MarketDataService={
  provider:localStorage.getItem(PROVIDER_KEY)||'mock',
  setProvider(name){this.provider=name||'mock';localStorage.setItem(PROVIDER_KEY,this.provider)},
  async quote(code){const x=assets.find(a=>a.code===code);if(!x)throw new Error('asset_not_found');return {...x,provider:this.provider,isMock:this.provider==='mock'}},
  async batch(codes){return Promise.all(codes.map(c=>this.quote(c).catch(()=>null))).then(a=>a.filter(Boolean))}
 };
 function reminders(){try{return new Set(JSON.parse(localStorage.getItem(REMINDER_KEY)||'[]'))}catch(e){return new Set()}}
 function saveReminders(s){localStorage.setItem(REMINDER_KEY,JSON.stringify([...s]))}
 function localParts(tz){const p=new Intl.DateTimeFormat('en-US',{timeZone:tz,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const get=t=>p.find(x=>x.type===t)?.value;return {day:get('weekday'),h:+get('hour'),m:+get('minute')}}
 function mins(o){return o.h*60+o.m}
 function range(now,a,b){return now>=a&&now<b}
 function sessionForAsset(x){let tz='UTC',windows=[],label='休市';if(x.tag==='A股'){tz='Asia/Shanghai';windows=[[570,690],[780,900]]}else if(x.tag==='港股'){tz='Asia/Hong_Kong';windows=[[570,720],[780,960]]}else if(x.region==='美股'){tz='America/New_York';windows=[[570,960]]}else if(x.region==='日本'){tz='Asia/Tokyo';windows=[[540,690],[750,930]]}else if(x.region==='韩国'){tz='Asia/Seoul';windows=[[540,930]]}else if(x.region==='欧洲'){tz='Europe/Berlin';windows=[[540,1050]]}else return {text:x.status||'交易中',cls:'wait',note:'全球/跨市场资产'};const o=localParts(tz),weekend=['Sat','Sun'].includes(o.day),n=mins(o),open=!weekend&&windows.some(w=>range(n,w[0],w[1]));if(open)label='交易中';else if(weekend)label='周末休市';else if(n<windows[0][0])label='未开盘';else label='已收盘';return {text:label,cls:open?'open':label==='未开盘'?'wait':'closed',note:'按常规交易时段估算，不含节假日'}}
 function marketStatusStrip(){const picks=[['上证指数','中国'],['日经225','日本'],['KOSPI','韩国'],['德国DAX','欧洲'],['纳斯达克100','美国']];return `<div class="live-sessions"><div class="section-head"><b>市场状态</b><span>自动判断 · 不含节假日</span></div><div class="live-session-grid">${picks.map(([n,l])=>{const x=assets.find(a=>a.name===n),s=x?sessionForAsset(x):{text:'—',cls:'closed'};return `<div><i class="dot ${s.cls}"></i><b>${l}</b><span>${s.text}</span></div>`}).join('')}</div></div>`}
 function enhanceHomeStatus(){if(state.page!=='首页')return;const c=el('content');if(!c||c.querySelector('.live-sessions'))return;const p=c.querySelector('.market-pulse');if(p)p.insertAdjacentHTML('afterend',marketStatusStrip());else c.insertAdjacentHTML('afterbegin',marketStatusStrip())}
 function searchScore(x,q){q=q.toLowerCase().trim();if(!q)return 0;const fields=[x.name,x.code,x.tag,x.group,x.region,x.type].filter(Boolean).map(v=>String(v).toLowerCase());let s=0;if(fields[0]===q||fields[1]===q)s+=100;if(fields.some(v=>v.startsWith(q)))s+=40;if(fields.some(v=>v.includes(q)))s+=15;return s}
 function searchResults(q){return assets.map(x=>({x,s:searchScore(x,q)})).filter(o=>o.s>0).sort((a,b)=>b.s-a.s||Math.abs(b.x.chg)-Math.abs(a.x.chg)).slice(0,24).map(o=>o.x)}
 function resultRows(list){if(!list.length)return `<div class="smart-empty"><b>没有找到相关资产</b><span>可以尝试股票代码、中文名、市场或类别，例如 NVDA、黄金、日本、半导体。</span></div>`;const groups={};list.forEach(x=>(groups[x.type]||(groups[x.type]=[])).push(x));return Object.entries(groups).map(([k,a])=>`<div class="search-group"><div class="search-group-title">${k}<span>${a.length}</span></div>${a.map(x=>{const s=x.type==='股票'?sessionForAsset(x):{text:x.status||'—',cls:'wait'};return `<button class="smart-result" data-name="${x.name}"><div><b>${x.name}</b><small>${x.code} · ${x.region} · ${x.tag||x.group||x.type}</small></div><div><strong>${x.price}</strong><span class="${x.chg>=0?'up':'down'}">${x.chg>=0?'+':''}${x.chg.toFixed(2)}%</span><em><i class="dot ${s.cls}"></i>${s.text}</em></div></button>`}).join('')}</div>`).join('')}
 function quickSearch(){return `<div class="search-welcome"><b>快速搜索</b><div class="search-chips">${['英伟达','贵州茅台','黄金','铜','美元指数','纳斯达克100'].map(x=>`<button data-query="${x}">${x}</button>`).join('')}</div><small>支持名称、代码、市场、类别与行业关键词。</small></div>`}
 function bindSearch(){const input=el('searchInput'),box=el('searchResults'),panel=el('searchPanel'),btn=el('searchBtn');if(!input||!box||!panel||!btn||btn.dataset.smartSearchBound==='1')return;btn.dataset.smartSearchBound='1';const render=q=>{box.innerHTML=q.trim()?resultRows(searchResults(q)):quickSearch();box.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;render(input.value)});box.querySelectorAll('.smart-result[data-name]').forEach(b=>b.onclick=()=>{panel.classList.add('hidden');openDetail(b.dataset.name)})};btn.addEventListener('click',()=>setTimeout(()=>{render(input.value);input.focus()},0));input.oninput=()=>render(input.value);input.addEventListener('focus',()=>{if(!input.value)render('')})}
 function reminderManager(){const r=reminders(),list=assets.filter(x=>r.has(x.name));return `<div class="reminder-card"><div class="section-head"><b>提醒管理</b><span>${list.length} 项</span></div>${list.length?`<div class="reminder-list">${list.map(x=>`<div><button data-rem-open="${x.name}"><b>${x.name}</b><span>${x.code} · ${x.price}</span></button><button class="rem-remove" data-rem-remove="${x.name}">关闭</button></div>`).join('')}</div><button class="clear-reminders" data-clear-reminders>清空全部提醒</button>`:`<div class="reminder-empty">还没有设置提醒。可在个股详情底部点击“提醒”。</div>`}<div class="provider-line"><span>行情数据层</span><b>${MarketDataService.provider==='mock'?'Mock 模拟源':MarketDataService.provider}</b></div></div>`}
 function enhanceWatchReminders(){if(state.page!=='自选')return;const c=el('content');if(!c||c.querySelector('.reminder-card'))return;c.insertAdjacentHTML('beforeend',reminderManager());c.querySelectorAll('[data-rem-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.remOpen));c.querySelectorAll('[data-rem-remove]').forEach(b=>b.onclick=()=>{const s=reminders();s.delete(b.dataset.remRemove);saveReminders(s);renderAll()});c.querySelector('[data-clear-reminders]')?.addEventListener('click',()=>{saveReminders(new Set());renderAll()})}
 function patchVisibleStatuses(){document.querySelectorAll('.row[data-name]').forEach(r=>{const x=assets.find(a=>a.name===r.dataset.name);if(!x||x.type!=='股票')return;const s=sessionForAsset(x);r.title=`${s.text} · ${s.note}`})}
 const baseRender=renderAll;renderAll=function(){baseRender();enhanceHomeStatus();enhanceWatchReminders();patchVisibleStatuses()};
 document.addEventListener('DOMContentLoaded',bindSearch);setTimeout(bindSearch,50);
})();