// V64: client history cache, calendar sync, refresh dedupe and gateway production-readiness UX.
(function(){
 const ENDPOINT_KEY='hw-proxy-endpoint-v1', HIST_KEY='hw-history-cache-v64', HIST_TTL=6*60*60*1000;
 const pendingHistory=new Map();
 function endpoint(){return (localStorage.getItem(ENDPOINT_KEY)||'').trim().replace(/\/$/,'')}
 function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}}
 function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
 function key(code,period){return `${String(code).toUpperCase()}::${period}`}
 function marketKind(m){return({US:'美股',CN:'A股',HK:'港股',JP:'日本',KR:'韩国',EU:'欧洲'})[m]||m}
 async function getJSON(path,timeout=8000){const base=endpoint();if(!base)throw new Error('proxy_endpoint_not_configured');const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const res=await fetch(base+path,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});const p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(p?.error||`http_${res.status}`);return p}finally{clearTimeout(timer)}}
 window.HistoryCacheService={all(){return readJSON(HIST_KEY,{})},get(code,period){const v=this.all()[key(code,period)];return v&&Date.now()-v.savedAt<HIST_TTL?v:null},put(code,period,payload){const all=this.all();all[key(code,period)]={payload,savedAt:Date.now()};writeJSON(HIST_KEY,all)},clear(){writeJSON(HIST_KEY,{})},count(){return Object.values(this.all()).filter(v=>Date.now()-v.savedAt<HIST_TTL).length}};
 if(window.MarketHistoryService){const raw=MarketHistoryService.load.bind(MarketHistoryService);MarketHistoryService.load=async function(code,period='1d',opts={}){const cached=HistoryCacheService.get(code,period);if(cached&&!opts.force)return {...cached.payload,_clientCache:true};const k=key(code,period);if(pendingHistory.has(k))return pendingHistory.get(k);const task=raw(code,period).then(p=>{HistoryCacheService.put(code,period,p);return p}).finally(()=>pendingHistory.delete(k));pendingHistory.set(k,task);return task}}
 if(window.MarketDataService){const rawRefresh=MarketDataService.refresh?.bind(MarketDataService);let pending=null;MarketDataService.refresh=async function(codes){if(pending)return pending;pending=Promise.resolve().then(()=>rawRefresh(codes)).finally(()=>{pending=null});return pending}}
 window.MarketCalendarService={
  async load(market){const p=await getJSON(`/calendar?market=${encodeURIComponent(market)}`,8000);const kind=marketKind(market);if(!Array.isArray(p.dates))throw new Error('invalid_calendar_payload');ExchangeCalendar?.install?.(kind,p.dates,p.source||'gateway');return p},
  async loadAll(){const cap=GatewayCapabilityService?.cached?.();if(!cap?.features?.calendar)throw new Error('gateway_calendar_not_configured');const markets=['US','CN','HK','JP','KR','EU'];const out=[];for(const m of markets){try{out.push({market:m,ok:true,data:await this.load(m)})}catch(e){out.push({market:m,ok:false,error:e.message})}}document.dispatchEvent(new CustomEvent('calendar:synced',{detail:out}));return out}
 };
 function cacheCard(){const count=HistoryCacheService.count();const cap=GatewayCapabilityService?.cached?.(),calendarReady=!!cap?.features?.calendar;return `<div class="v64-ops"><div class="section-head"><b>数据稳定性</b><span>V64</span></div><div class="v64-ops-grid"><div><small>历史缓存</small><b>${count} 组</b><span>本机 6 小时</span></div><div><small>请求合并</small><b>已启用</b><span>避免重复刷新</span></div><div><small>网关缓存</small><b>${cap?.cache?'已声明':'待检测'}</b><span>${cap?.cache?`报价 ${cap.cache.quotesSeconds}s`:'读取 /health'}</span></div><div><small>交易日历</small><b>${calendarReady?'可同步':'未配置'}</b><span>${calendarReady?'来自网关':'常规时段估算'}</span></div></div><div class="v64-actions"><button data-v64-calendar ${calendarReady?'':'disabled'}>同步交易日历</button><button data-v64-clear>清空历史缓存</button></div><div class="v64-result" data-v64-result>${calendarReady?'网关已声明日历能力，可手动同步。':'当前未配置交易日历源。'}</div></div>`}
 function installOps(){if(state.page!=='数据')return;const c=el('content');if(!c||c.querySelector('.v64-ops'))return;const s=c.querySelector('.session-engine')||c.querySelector('.route-matrix');if(s)s.insertAdjacentHTML('afterend',cacheCard());else c.insertAdjacentHTML('beforeend',cacheCard());const out=c.querySelector('[data-v64-result]'),sync=c.querySelector('[data-v64-calendar]');sync?.addEventListener('click',async()=>{sync.disabled=true;sync.textContent='同步中…';out.textContent='正在从网关读取各市场交易日历…';try{const r=await MarketCalendarService.loadAll(),ok=r.filter(x=>x.ok),fail=r.filter(x=>!x.ok);out.textContent=`同步完成 · ${ok.length} 个市场成功${fail.length?`，${fail.length} 个失败`:''}`;renderAll()}catch(e){out.textContent=`同步失败 · ${e.message}`}finally{sync.disabled=false;sync.textContent='同步交易日历'}});c.querySelector('[data-v64-clear]')?.addEventListener('click',()=>{HistoryCacheService.clear();out.textContent='历史行情本地缓存已清空';setTimeout(()=>renderAll(),250)})}
 function patchHistorySource(){const box=document.querySelector('.v63-history');if(!box||box.dataset.v64)return;box.dataset.v64='1';const load=box.querySelector('[data-v63-history-load]'),stateBox=box.querySelector('[data-v63-history-state]');if(!load)return;const original=load.onclick;load.addEventListener('click',()=>{setTimeout(()=>{const active=box.querySelector('[data-v63-period].active')?.dataset.v63Period||'1d',code=new URL(location.href).searchParams.get('asset'),hit=code&&HistoryCacheService.get(code,active);if(hit&&stateBox)stateBox.textContent=`本机缓存可用 · ${new Date(hit.savedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`},0)})}
 const baseOpen=openDetail;openDetail=function(name){baseOpen(name);patchHistorySource()};
 const baseRender=renderAll;renderAll=function(){baseRender();installOps()};
 document.addEventListener('gateway:capabilities',()=>{if(state.page==='数据')renderAll()});
})();
