// V66: unified watchlist manager, in-app group sheet, runtime cleanup and refresh-state polish.
(function(){
 const GROUP_KEY='hw-watch-groups-v1', ASSIGN_KEY='hw-watch-group-assign-v1';
 function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}}
 function writeJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
 function groups(){const g=readJSON(GROUP_KEY,['核心','观察']);return Array.isArray(g)?g:[]}
 function assigns(){const a=readJSON(ASSIGN_KEY,{});return a&&typeof a==='object'?a:{}}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function saveGroups(g){writeJSON(GROUP_KEY,[...new Set(g.map(x=>String(x).trim().slice(0,8)).filter(Boolean))])}
 function assign(name,group){const a=assigns();if(group)a[name]=group;else delete a[name];writeJSON(ASSIGN_KEY,a)}
 function renameGroup(oldName,newName){newName=String(newName||'').trim().slice(0,8);if(!newName||newName===oldName)return false;const g=groups();if(g.includes(newName))return false;saveGroups(g.map(x=>x===oldName?newName:x));const a=assigns();Object.keys(a).forEach(k=>{if(a[k]===oldName)a[k]=newName});writeJSON(ASSIGN_KEY,a);return true}
 function deleteGroup(name){saveGroups(groups().filter(x=>x!==name));const a=assigns();Object.keys(a).forEach(k=>{if(a[k]===name)delete a[k]});writeJSON(ASSIGN_KEY,a)}
 window.WatchGroupService={...(window.WatchGroupService||{}),all:groups,assignments:assigns,assign,create(name){const n=String(name||'').trim().slice(0,8);if(!n||groups().includes(n))return false;saveGroups([...groups(),n]);return true},rename:renameGroup,remove:deleteGroup};
 function selected(){return assets.filter(a=>favs.has(a.name))}
 function countFor(g){const a=assigns();return selected().filter(x=>a[x.name]===g).length}
 function groupBar(){const gs=groups();return `<div class="v66-watch"><div class="v66-watch-head"><div><b>自选分组</b><span>${selected().length} 项</span></div><button data-v66-manage>管理分组</button></div><div class="v66-group-tabs"><button class="active" data-v66-group="全部">全部 <em>${selected().length}</em></button>${gs.map(g=>`<button data-v66-group="${esc(g)}">${esc(g)} <em>${countFor(g)}</em></button>`).join('')}<button data-v66-group="未分组">未分组 <em>${selected().filter(x=>!assigns()[x.name]).length}</em></button></div></div>`}
 function rowAssign(root){root.querySelectorAll('.row[data-name]').forEach(r=>{r.querySelector('.group-assign')?.remove();const name=r.dataset.name,wrap=document.createElement('div');wrap.className='v66-row-group';wrap.innerHTML=`<select aria-label="分组 ${esc(name)}"><option value="">未分组</option>${groups().map(g=>`<option value="${esc(g)}" ${assigns()[name]===g?'selected':''}>${esc(g)}</option>`).join('')}</select>`;r.appendChild(wrap);const s=wrap.querySelector('select');s.onclick=e=>e.stopPropagation();s.onchange=e=>{e.stopPropagation();assign(name,e.target.value);installWatchManager(true)}})}
 function managerSheet(){let d=document.getElementById('v66GroupSheet');if(d)return d;d=document.createElement('div');d.id='v66GroupSheet';d.className='v66-sheet hidden';d.innerHTML=`<div class="v66-sheet-mask" data-v66-close></div><div class="v66-sheet-panel"><div class="v66-sheet-title"><b>管理自选分组</b><button data-v66-close>完成</button></div><div data-v66-group-list></div><div class="v66-new-row"><input data-v66-new maxlength="8" placeholder="新分组名称，最多 8 个字"><button data-v66-add>新建</button></div><div class="v66-sheet-msg" data-v66-msg></div></div>`;document.body.appendChild(d);d.querySelectorAll('[data-v66-close]').forEach(b=>b.onclick=()=>d.classList.add('hidden'));d.querySelector('[data-v66-add]').onclick=()=>{const input=d.querySelector('[data-v66-new]'),n=input.value.trim();if(!WatchGroupService.create(n)){msg('名称为空或已存在');return}input.value='';renderSheet();installWatchManager(true)};return d}
 function msg(t){const d=managerSheet(),m=d.querySelector('[data-v66-msg]');m.textContent=t;setTimeout(()=>{if(m.textContent===t)m.textContent=''},1800)}
 function renderSheet(){const d=managerSheet(),list=d.querySelector('[data-v66-group-list]'),gs=groups();list.innerHTML=gs.length?gs.map(g=>`<div class="v66-manage-row" data-g="${esc(g)}"><div><b>${esc(g)}</b><span>${countFor(g)} 项</span></div><button data-rename="${esc(g)}">重命名</button><button class="danger" data-delete="${esc(g)}">删除</button></div>`).join(''):`<div class="v66-no-group">暂无自定义分组</div>`;list.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{const row=b.closest('.v66-manage-row'),old=b.dataset.rename;if(row.querySelector('input'))return;const left=row.querySelector('div');left.innerHTML=`<input maxlength="8" value="${esc(old)}" data-rename-input><span>${countFor(old)} 项</span>`;b.textContent='保存';b.onclick=()=>{const n=row.querySelector('[data-rename-input]').value;if(!renameGroup(old,n)){msg('名称为空、重复或没有变化');renderSheet();return}renderSheet();installWatchManager(true)}});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const g=b.dataset.delete;b.textContent='再次点击确认';b.classList.add('confirm');const second=()=>{deleteGroup(g);renderSheet();installWatchManager(true)};setTimeout(()=>b.onclick=second,0)})}
 function openSheet(){const d=managerSheet();renderSheet();d.classList.remove('hidden');setTimeout(()=>d.querySelector('[data-v66-new]')?.focus(),120)}
 function installWatchManager(force=false){if(state.page!=='自选')return;const c=el('content'),list=c?.querySelector('.watch-list');if(!c||!list)return;c.querySelector('.watch-groups')?.remove();c.querySelector('.custom-group-wrap')?.remove();c.querySelector('.v66-watch')?.remove();list.insertAdjacentHTML('beforebegin',groupBar());let active='全部';const renderList=()=>{const a=assigns();const items=selected().filter(x=>active==='全部'?true:active==='未分组'?!a[x.name]:a[x.name]===active);list.innerHTML=rows(items);list.querySelectorAll('.row[data-name]').forEach(r=>r.onclick=()=>openDetail(r.dataset.name));rowAssign(list)};c.querySelectorAll('[data-v66-group]').forEach(b=>b.onclick=()=>{active=b.dataset.v66Group;c.querySelectorAll('[data-v66-group]').forEach(z=>z.classList.toggle('active',z===b));renderList()});c.querySelector('[data-v66-manage]')?.addEventListener('click',openSheet);rowAssign(list)}
 function polishRefresh(){if(state.page!=='首页')return;const t=document.querySelector('[data-refresh-time]');if(t&&!MarketDataService?.lastUpdated)t.textContent='尚未刷新'}
 function architectureNote(){if(state.page!=='数据')return;const c=el('content'),diag=c?.querySelector('.v65-diag');if(!diag||diag.querySelector('.v66-arch'))return;diag.insertAdjacentHTML('beforeend','<div class="v66-arch"><b>V66 收敛进度</b><span>自选分组已迁移到统一 ProductRuntime；旧的类型分组与 V58 自定义分组 UI 会在渲染后被替换，不再叠加显示。</span></div>')}
 if(window.ProductRuntime){ProductRuntime.afterRender(installWatchManager);ProductRuntime.afterRender(polishRefresh);ProductRuntime.afterRender(architectureNote);setTimeout(()=>ProductRuntime.run(),0)}else{const base=renderAll;renderAll=function(){base();installWatchManager();polishRefresh();architectureNote()}}
})();