// 行情万象 · Cloudflare Worker 行情网关 V63
// 当前真实 Provider：Alpha Vantage（美股报价 + 日/周/月K）。
// A股/港股路由已预留，但在配置对应服务端 Provider 前不会伪装成可用行情。
// Secret：ALPHA_VANTAGE_API_KEY（真实接入时必填）
// 可选：ALLOW_ORIGIN，建议正式环境设为 https://yswgo.github.io

const AV_BASE='https://www.alphavantage.co/query';
const MAX_CODES=5;
const SUPPORTED_US=/^[A-Z][A-Z0-9.-]{0,9}$/;

function cors(env){return {
  'Access-Control-Allow-Origin':env.ALLOW_ORIGIN||'*',
  'Access-Control-Allow-Methods':'GET,OPTIONS',
  'Access-Control-Allow-Headers':'Content-Type,Accept',
  'Cache-Control':'no-store'
}}
function json(data,status,env){return new Response(JSON.stringify(data),{status,headers:{...cors(env),'Content-Type':'application/json; charset=utf-8'}})}
function n(v){const x=Number(String(v??'').replace('%',''));return Number.isFinite(x)?x:null}
function marketOf(code){const s=String(code||'').toUpperCase();if(/^\d{6}$/.test(s))return'CN';if(/^\d{4}\.HK$/.test(s))return'HK';if(SUPPORTED_US.test(s))return'US';return'OTHER'}
function providerFor(market,env){if(market==='US'&&env.ALPHA_VANTAGE_API_KEY)return'alpha_vantage';if(market==='CN')return env.CN_PROVIDER_URL?'cn_proxy':null;if(market==='HK')return env.HK_PROVIDER_URL?'hk_proxy':null;return null}
function normalizeUSQuote(symbol,payload){const q=payload?.['Global Quote'];if(!q||!q['05. price'])return null;return {code:symbol,name:symbol,price:q['05. price'],chg:n(q['10. change percent'])??0,status:'按数据源',provider:'alpha_vantage',market:'US',delay:'provider',isMock:false,timestamp:Date.now()}}
async function avQuery(params,key){const url=new URL(AV_BASE);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));url.searchParams.set('apikey',key);const res=await fetch(url.toString(),{headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`upstream_http_${res.status}`);const payload=await res.json();if(payload?.Note||payload?.Information)throw new Error('upstream_rate_limited');if(payload?.['Error Message'])throw new Error('upstream_invalid_symbol');return payload}
async function usQuote(symbol,env){const payload=await avQuery({function:'GLOBAL_QUOTE',symbol},env.ALPHA_VANTAGE_API_KEY);const q=normalizeUSQuote(symbol,payload);if(!q)throw new Error('quote_unavailable');return q}
async function externalProxyQuote(code,market,env){const base=market==='CN'?env.CN_PROVIDER_URL:env.HK_PROVIDER_URL;if(!base)throw new Error('provider_not_configured');const token=market==='CN'?env.CN_PROVIDER_TOKEN:env.HK_PROVIDER_TOKEN;const u=new URL(base.replace(/\/$/,'')+'/quote');u.searchParams.set('code',code);const headers={Accept:'application/json'};if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(u.toString(),{headers});if(!res.ok)throw new Error(`upstream_http_${res.status}`);const q=await res.json();if(!q||q.price==null)throw new Error('quote_unavailable');return {code,name:q.name||code,price:String(q.price),chg:n(q.chg)??0,status:q.status||'按数据源',provider:market==='CN'?'cn_proxy':'hk_proxy',market,delay:q.delay??'provider',isMock:false,timestamp:Number(q.timestamp)||Date.now()}}
async function quoteOne(code,env){const market=marketOf(code),provider=providerFor(market,env);if(!provider)throw new Error(market==='OTHER'?'unsupported_symbol':'provider_not_configured');if(provider==='alpha_vantage')return usQuote(code,env);return externalProxyQuote(code,market,env)}
async function quotes(request,env){const url=new URL(request.url),raw=(url.searchParams.get('codes')||'').split(',').map(s=>s.trim()).filter(Boolean).slice(0,MAX_CODES);if(!raw.length)return json({error:'missing_codes'},400,env);const data=[],errors=[];for(const code of raw){try{data.push(await quoteOne(code,env))}catch(e){errors.push({code,market:marketOf(code),error:e.message||'quote_failed'})}}return json({data,errors,meta:{gateway:'v63',requested:raw.length,returned:data.length,timestamp:Date.now()}},data.length?200:502,env)}
function normalizeSeries(payload,key,limit=160){const series=payload?.[key];if(!series)return[];return Object.entries(series).slice(0,limit).map(([date,v])=>({ts:new Date(`${date}T00:00:00Z`).getTime(),o:n(v['1. open']),h:n(v['2. high']),l:n(v['3. low']),c:n(v['4. close']),v:n(v['5. volume'])})).filter(p=>p.c!=null).sort((a,b)=>a.ts-b.ts)}
function historySpec(period){const p=String(period||'1d').toLowerCase();if(['1d','daily'].includes(p))return{period:'1d',fn:'TIME_SERIES_DAILY',key:'Time Series (Daily)',params:{outputsize:'compact'}};if(['1w','weekly'].includes(p))return{period:'1w',fn:'TIME_SERIES_WEEKLY',key:'Weekly Time Series',params:{}};if(['1m','monthly'].includes(p))return{period:'1m',fn:'TIME_SERIES_MONTHLY',key:'Monthly Time Series',params:{}};return null}
async function history(request,env){const url=new URL(request.url),code=(url.searchParams.get('code')||'').trim(),period=(url.searchParams.get('period')||'1d').toLowerCase();if(!code)return json({error:'missing_code'},400,env);const market=marketOf(code);if(market!=='US')return json({error:'history_provider_not_configured',market},501,env);if(!env.ALPHA_VANTAGE_API_KEY)return json({error:'server_not_configured'},503,env);const spec=historySpec(period);if(!spec)return json({error:'unsupported_period',supported:['1d','1w','1m']},400,env);try{const payload=await avQuery({function:spec.fn,symbol:code,...spec.params},env.ALPHA_VANTAGE_API_KEY);const points=normalizeSeries(payload,spec.key);if(!points.length)throw new Error('history_unavailable');return json({code,period:spec.period,market:'US',provider:'alpha_vantage',isMock:false,points,meta:{count:points.length,timestamp:Date.now()}},200,env)}catch(e){return json({error:e.message||'history_failed',code},502,env)}}
function health(env){const providers={US:{configured:!!env.ALPHA_VANTAGE_API_KEY,provider:'alpha_vantage',quotes:true,history:['1d','1w','1m']},CN:{configured:!!env.CN_PROVIDER_URL,provider:'cn_proxy',quotes:!!env.CN_PROVIDER_URL,history:[]},HK:{configured:!!env.HK_PROVIDER_URL,provider:'hk_proxy',quotes:!!env.HK_PROVIDER_URL,history:[]}};return {ok:true,service:'hangqing-wanxiang-gateway',version:'63',providers,scope:Object.entries(providers).filter(([,v])=>v.configured).map(([k])=>k),limits:{quotesPerRequest:MAX_CODES},features:{historyPeriods:['1d','1w','1m'],calendar:false},timestamp:Date.now()}}
export default {async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(env)});const url=new URL(request.url);if(url.pathname==='/health'&&request.method==='GET')return json(health(env),200,env);if(url.pathname==='/quotes'&&request.method==='GET')return quotes(request,env);if(url.pathname==='/history'&&request.method==='GET')return history(request,env);return json({error:'not_found'},404,env)}};
