// 行情万象 · Cloudflare Worker 行情网关 V74
// Webull Sandbox(AAPL) -> Twelve Data -> Alpha Vantage -> stale real cache.
// Sandbox is explicitly labeled and never presented as production market data.
const AV_BASE='https://www.alphavantage.co/query',TD_BASE='https://api.twelvedata.com',WB_SANDBOX='https://api.sandbox.webull.hk';
const MAX_CODES=5,QUOTE_TTL=20,STALE_TTL=6*60*60,HISTORY_TTL=6*60*60,CALENDAR_TTL=12*60*60;
const US_SYMBOL=/^[A-Z][A-Z0-9-]{0,7}(?:\.[A-Z])?$/;
// Official Webull shared sandbox account #1. Override with env WEBULL_SANDBOX_APP_KEY / SECRET if desired.
const WB_PUBLIC_KEY='4b2b7acd2bf0d30d8aea173fceefa238',WB_PUBLIC_SECRET='840b4353a6a31ce3ab91e2f99a510272';
let wbToken=null;
function cors(env){return{'Access-Control-Allow-Origin':env.ALLOW_ORIGIN||'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Accept','Cache-Control':'no-store'}}
function json(data,status,env,extra={}){return new Response(JSON.stringify(data),{status,headers:{...cors(env),'Content-Type':'application/json; charset=utf-8',...extra}})}
function n(v){const x=Number(String(v??'').replace('%',''));return Number.isFinite(x)?x:null}
function marketOf(code){const s=String(code||'').toUpperCase().trim();if(/^\d{6}$/.test(s))return'CN';if(/^\d{4}\.HK$/.test(s))return'HK';if(/\.T$/.test(s))return'JP';if(/\.KS$/.test(s))return'KR';if(/\.(DE|AS|PA)$/.test(s))return'EU';if(US_SYMBOL.test(s))return'US';return'OTHER'}
function currencyFor(m,q={}){return q.currency||({US:'USD',CN:'CNY',HK:'HKD'})[m]||null}
function quoteV2(o){const pct=n(o.chgPct)??0,fetchTs=Number(o.fetchedAt||o.timestamp)||Date.now();return{schemaVersion:2,code:String(o.code),name:o.name||String(o.code),price:String(o.price),change:n(o.change),chgPct:pct,chg:pct,currency:o.currency||null,status:o.status||'按数据源',provider:o.provider||o.source||'unknown',source:o.source||o.provider||'unknown',market:o.market||marketOf(o.code),delayed:typeof o.delayed==='boolean'?o.delayed:null,delayMinutes:Number.isFinite(Number(o.delayMinutes))?Number(o.delayMinutes):null,isMock:false,isSandbox:!!o.isSandbox,quoteTime:o.quoteTime||null,quoteDate:o.quoteDate||null,fetchedAt:fetchTs,timestamp:fetchTs,_edgeCache:!!o._edgeCache,_staleCache:!!o._staleCache}}
function cacheReq(key){return new Request(`https://hangqing-cache.invalid/${encodeURIComponent(key)}`)}
async function cacheGet(key){const c=globalThis.caches?.default;if(!c)return null;try{const r=await c.match(cacheReq(key));return r?await r.json():null}catch{return null}}
async function cachePut(key,value,ttl){const c=globalThis.caches?.default;if(!c)return;try{await c.put(cacheReq(key),new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json','Cache-Control':`public, max-age=${ttl}`}}))}catch{}}
async function edgeCached(key,ttl,producer){const hit=await cacheGet(key);if(hit){hit._edgeCache=true;return hit}const value=await producer();await cachePut(key,value,ttl);return value}
function rfc3986(s){return encodeURIComponent(String(s)).replace(/[!'()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase())}
function b64(buf){let s='';new Uint8Array(buf).forEach(b=>s+=String.fromCharCode(b));return btoa(s)}
async function sha256Hex(s){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function hmac256(source,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret+'&'),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(source)))}
async function wbSigned(path,queries,body,version,env,accessToken){const appKey=env.WEBULL_SANDBOX_APP_KEY||WB_PUBLIC_KEY,secret=env.WEBULL_SANDBOX_APP_SECRET||WB_PUBLIC_SECRET,host='api.sandbox.webull.hk',timestamp=new Date().toISOString().replace(/\.\d{3}Z$/,'Z'),nonce=crypto.randomUUID().replace(/-/g,'');const sign={host,'x-app-key':appKey,'x-signature-algorithm':'HMAC-SHA256','x-signature-nonce':nonce,'x-signature-version':'1.0','x-timestamp':timestamp};Object.entries(queries||{}).forEach(([k,v])=>sign[k]=String(v));const parts=Object.entries(sign).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`);let raw=path+'&'+parts.join('&');if(body!==null&&body!==undefined)raw+='&'+await sha256Hex(JSON.stringify(body));const signature=await hmac256(rfc3986(raw),secret);const headers={'Accept':'application/json','Content-Type':'application/json','x-app-key':appKey,'x-timestamp':timestamp,'x-signature-algorithm':'HMAC-SHA256','x-signature-version':'1.0','x-signature-nonce':nonce,'x-version':version,'x-signature':signature};if(accessToken)headers['x-access-token']=accessToken;return headers}
async function wbRequest(path,{queries={},body=null,version='v2',token=true}={},env){const u=new URL(WB_SANDBOX+path);Object.entries(queries).forEach(([k,v])=>u.searchParams.set(k,v));let accessToken=null;if(token)accessToken=await wbAccessToken(env);const headers=await wbSigned(path,queries,body,version,env,accessToken),r=await fetch(u,{method:body===null?'GET':'POST',headers,body:body===null?undefined:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(r.status===403?'webull_permission_denied':r.status===401?'webull_auth_failed':`webull_http_${r.status}`);e.detail=p;throw e}return p}
async function wbAccessToken(env){if(wbToken?.token&&(!wbToken.expires||Number(wbToken.expires)>Date.now()+60000))return wbToken.token;const path='/auth/tokens/create',body={},headers=await wbSigned(path,{},body,'v3',env,null),r=await fetch(WB_SANDBOX+path,{method:'POST',headers,body:'{}'}),p=await r.json().catch(()=>({}));if(!r.ok||!p?.token)throw new Error(r.status===401?'webull_auth_failed':`webull_token_${r.status}`);if(p.status&&p.status!=='NORMAL')throw new Error(`webull_token_${String(p.status).toLowerCase()}`);wbToken=p;return p.token}
async function wbQuote(symbol,env){if(symbol!=='AAPL')throw new Error('webull_sandbox_symbol_limited');const p=await wbRequest('/openapi/market-data/stock/snapshot',{queries:{symbols:symbol,category:'US_STOCK',extend_hour_required:'true',overnight_required:'true'}},env),q=Array.isArray(p)?p[0]:p?.data?.[0];if(!q||q.price==null)throw new Error('webull_quote_unavailable');const ratio=n(q.change_ratio),pct=ratio==null?null:ratio*100,ts=Number(q.last_trade_time)||null;return quoteV2({code:symbol,name:'Apple',price:q.price,change:q.change,chgPct:pct,currency:'USD',provider:'webull_sandbox',source:'webull_sandbox',market:'US',status:'Webull 沙盒测试',delayed:null,isSandbox:true,quoteTime:ts?new Date(ts).toISOString():null,quoteDate:ts?new Date(ts).toISOString().slice(0,10):null,fetchedAt:Date.now()})}
async function avQuery(params,key){const u=new URL(AV_BASE);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set('apikey',key);const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`upstream_http_${r.status}`);const p=await r.json();if(p?.Note||p?.Information)throw new Error('upstream_rate_limited');if(p?.['Error Message'])throw new Error('upstream_invalid_symbol');return p}
async function avQuote(symbol,env){if(!env.ALPHA_VANTAGE_API_KEY)throw new Error('provider_not_configured');const p=await avQuery({function:'GLOBAL_QUOTE',symbol},env.ALPHA_VANTAGE_API_KEY),q=p?.['Global Quote'];if(!q?.['05. price'])throw new Error('quote_unavailable');return quoteV2({code:symbol,price:q['05. price'],change:q['09. change'],chgPct:q['10. change percent'],currency:'USD',provider:'alpha_vantage',market:'US',delayed:null,quoteDate:q['07. latest trading day'],fetchedAt:Date.now()})}
async function tdGet(path,params,key){const u=new URL(TD_BASE+path);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set('apikey',key);const r=await fetch(u,{headers:{Accept:'application/json'}});const p=await r.json().catch(()=>({}));if(!r.ok||p?.status==='error'){const msg=String(p?.message||'').toLowerCase();if(r.status===429||msg.includes('credit')||msg.includes('limit'))throw new Error('upstream_rate_limited');throw new Error(p?.code?`twelve_${p.code}`:`upstream_http_${r.status}`)}return p}
async function tdQuote(symbol,env){if(!env.TWELVE_DATA_API_KEY)throw new Error('provider_not_configured');const q=await tdGet('/quote',{symbol},env.TWELVE_DATA_API_KEY);if(q?.close==null)throw new Error('quote_unavailable');const price=n(q.close),prev=n(q.previous_close),change=n(q.change)??(price!=null&&prev!=null?price-prev:null),pct=n(q.percent_change)??(change!=null&&prev?change/prev*100:null);return quoteV2({code:symbol,name:q.name||symbol,price,change,chgPct:pct,currency:q.currency||'USD',provider:'twelve_data',source:'twelve_data',market:'US',delayed:null,quoteTime:q.datetime||null,quoteDate:q.datetime?String(q.datetime).slice(0,10):null,fetchedAt:Date.now()})}
async function usFresh(symbol,env){const errors=[];if(symbol==='AAPL'&&env.WEBULL_SANDBOX_ENABLED!=='false'){try{return await wbQuote(symbol,env)}catch(e){errors.push({provider:'webull_sandbox',error:e.message})}}if(env.TWELVE_DATA_API_KEY){try{return await tdQuote(symbol,env)}catch(e){errors.push({provider:'twelve_data',error:e.message})}}if(env.ALPHA_VANTAGE_API_KEY){try{return await avQuote(symbol,env)}catch(e){errors.push({provider:'alpha_vantage',error:e.message})}}const err=new Error(errors.at(-1)?.error||'provider_not_configured');err.providers=errors;throw err}
async function usQuote(symbol,env){const freshKey=`quote:US:${symbol}:v74`,staleKey=`stale:US:${symbol}:v74`;const hit=await cacheGet(freshKey);if(hit){hit._edgeCache=true;return hit}try{const q=await usFresh(symbol,env);await Promise.all([cachePut(freshKey,q,QUOTE_TTL),cachePut(staleKey,q,STALE_TTL)]);return q}catch(e){const stale=await cacheGet(staleKey);if(stale){stale._edgeCache=true;stale._staleCache=true;stale.status='缓存行情';return stale}throw e}}
function tushareCode(code){const s=String(code).toUpperCase();if(/^[0-9]{6}$/.test(s)){if(s.startsWith('6')||s.startsWith('68'))return s+'.SH';if(s.startsWith('8')||s.startsWith('4'))return s+'.BJ';return s+'.SZ'}return s}
async function stockTodayProbe(api_name,params,env){const base=(env.STOCKTODAY_URL||'https://stocktoday.citydata.club').replace(/\/$/,'');const r=await fetch(base+'/'+api_name,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','User-Agent':'hangqing-wanxiang-gateway/82'},body:JSON.stringify({api_name,token:env.STOCKTODAY_TOKEN,params,fields:''})});const raw=await r.text();let body={};try{body=JSON.parse(raw)}catch{}return{api_name,httpStatus:r.status,ok:r.ok,code:body?.code??null,msg:body?.msg??null,hasData:!!body?.data,bodyPreview:raw.slice(0,300)}}
async function stockTodayAuthTest(request,env){if(!env.STOCKTODAY_TOKEN)return json({ok:false,error:'stocktoday_not_configured'},503,env);const [auth,daily,rt]=await Promise.all([stockTodayProbe('token_info',{},env),stockTodayProbe('daily',{ts_code:'600519.SH',start_date:'20260101',end_date:'20260102'},env),stockTodayProbe('rt_k',{ts_code:'600519.SH'},env)]);return json({ok:auth.ok&&daily.ok&&rt.ok,provider:'stocktoday',tests:{token_info:auth,daily,rt_k:rt},note:'仅返回接口状态，不返回 Token。'},200,env)}
async function stockTodayAQuote(code,env){if(!env.STOCKTODAY_TOKEN)throw new Error('stocktoday_not_configured');const ts=tushareCode(code),base=(env.STOCKTODAY_URL||'https://stocktoday.cn/api/tools').replace(/\/$/,''),r=await fetch(base+'/call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_name:'rt_k',token:env.STOCKTODAY_TOKEN,params:{ts_code:ts},fields:''})});const raw=await r.text();let p={};try{p=JSON.parse(raw)}catch{}if(!r.ok)throw new Error('stocktoday_http_'+r.status+(p?.msg?'_'+p.msg:('_'+raw.slice(0,200).replace(/\\s+/g,' '))));if(p?.code&&p.code!==0)throw new Error('stocktoday_'+(p.msg||'api_error'));const row=p?.data?.items?.[0],fields=p?.data?.fields||[];if(!row)throw new Error('stocktoday_quote_unavailable_'+JSON.stringify(p).slice(0,500));const q=Array.isArray(row)?Object.fromEntries(fields.map((f,i)=>[f,row[i]])):row,price=Number(q.close),prev=Number(q.pre_close);if(!Number.isFinite(price))throw new Error('stocktoday_price_unavailable');const change=Number.isFinite(prev)?price-prev:null,pct=Number.isFinite(prev)&&prev?change/prev*100:null;return quoteV2({code,name:q.name||code,price,change,chgPct:pct,currency:'CNY',status:'StockToday 实时行情',provider:'stocktoday_rt_k',source:'stocktoday',market:'CN',delayed:false,delayMinutes:0,quoteTime:q.trade_time,fetchedAt:Date.now()})}
async function stockTodayAQuoteCached(code,env){const key='quote:CN:'+code+':stocktoday:v1',staleKey='stale:CN:'+code+':stocktoday:v1',hit=await cacheGet(key);if(hit){hit._edgeCache=true;return hit}try{const q=await stockTodayAQuote(code,env);await Promise.all([cachePut(key,q,QUOTE_TTL),cachePut(staleKey,q,STALE_TTL)]);return q}catch(e){const stale=await cacheGet(staleKey);if(stale){stale._edgeCache=true;stale._staleCache=true;stale.status='缓存行情';return stale}throw e}}
async function tushareAQuote(code,env){if(!env.TUSHARE_TOKEN)throw new Error('tushare_not_configured');const ts=tushareCode(code),r=await fetch('https://api.tushare.pro',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_name:'rt_k',token:env.TUSHARE_TOKEN,params:{ts_code:ts},fields:'ts_code,name,pre_close,high,open,low,close,vol,amount,trade_time'})});if(!r.ok)throw new Error('tushare_http_'+r.status);const p=await r.json();if(p?.code&&p.code!==0)throw new Error('tushare_'+(p.msg||'api_error'));const row=p?.data?.items?.[0],fields=p?.data?.fields||[];if(!row)throw new Error('tushare_quote_unavailable');const q=Object.fromEntries(fields.map((f,i)=>[f,row[i]])),price=Number(q.close),prev=Number(q.pre_close);if(!Number.isFinite(price))throw new Error('tushare_price_unavailable');const change=Number.isFinite(prev)?price-prev:null,pct=Number.isFinite(prev)&&prev?change/prev*100:null;return quoteV2({code,name:q.name||code,price,change,chgPct:pct,currency:'CNY',status:'Tushare 实时日线',provider:'tushare_rt_k',source:'tushare',market:'CN',delayed:false,delayMinutes:0,quoteTime:q.trade_time,fetchedAt:Date.now()})}
async function tushareAQuoteCached(code,env){const key='quote:CN:'+code+':tushare:v83',staleKey='stale:CN:'+code+':tushare:v83',hit=await cacheGet(key);if(hit){hit._edgeCache=true;return hit}try{const q=await tushareAQuote(code,env);await Promise.all([cachePut(key,q,QUOTE_TTL),cachePut(staleKey,q,STALE_TTL)]);return q}catch(e){const stale=await cacheGet(staleKey);if(stale){stale._edgeCache=true;stale._staleCache=true;stale.status='缓存行情';return stale}throw e}}
async function externalProxyFresh(code,market,env){const base=market==='CN'?env.CN_PROVIDER_URL:env.HK_PROVIDER_URL;if(!base)throw new Error('provider_not_configured');const token=market==='CN'?env.CN_PROVIDER_TOKEN:env.HK_PROVIDER_TOKEN,u=new URL(base.replace(/\/$/,'')+'/quote');u.searchParams.set('code',code);const headers={Accept:'application/json'};if(token)headers.Authorization='Bearer '+token;const r=await fetch(u,{headers});if(!r.ok)throw new Error('upstream_http_'+r.status);const payload=await r.json();const q=payload?.data?.[0]||payload?.data||payload?.quote||payload;if(!q)throw new Error('quote_unavailable');const price=q.price??q.latestPrice??q.last??q.close,change=q.change??q.changeAmount??q.delta,pct=q.chgPct??q.changePct??q.changePercent??q.pct; if(price==null)throw new Error('quote_unavailable');return quoteV2({code:q.code||code,name:q.name||q.short_name||q.symbol||code,price,change,chgPct:pct,currency:currencyFor(market,q),status:q.status,provider:market==='CN'?'cn_proxy':'hk_proxy',source:q.source||q.provider||'domestic_provider',market,delayed:q.delayed,delayMinutes:q.delayMinutes,quoteTime:q.quoteTime||q.tradeTime||q.timestamp,quoteDate:q.quoteDate,fetchedAt:q.fetchedAt||q.timestamp})}
async function externalProxyQuote(code,market,env){const key='quote:'+market+':'+code+':v83',staleKey='stale:'+market+':'+code+':v83',hit=await cacheGet(key);if(hit){hit._edgeCache=true;return hit}try{const q=await externalProxyFresh(code,market,env);await Promise.all([cachePut(key,q,QUOTE_TTL),cachePut(staleKey,q,STALE_TTL)]);return q}catch(e){const stale=await cacheGet(staleKey);if(stale){stale._edgeCache=true;stale._staleCache=true;stale.status='缓存行情';return stale}throw e}}
function quoteOne(code,env){const m=marketOf(code);if(m==='US')return usQuote(code,env);if(m==='CN'){if(env.STOCKTODAY_TOKEN) return stockTodayAQuoteCached(code,env);if(env.TUSHARE_TOKEN) return tushareAQuoteCached(code,env);return externalProxyQuote(code,m,env)}if(m==='HK')return externalProxyQuote(code,m,env);throw new Error(m==='OTHER'?'unsupported_symbol':'provider_not_configured')}
async function quotes(request,env){const u=new URL(request.url),raw=[...new Set((u.searchParams.get('codes')||'').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean))].slice(0,MAX_CODES);if(!raw.length)return json({error:'missing_codes'},400,env);const settled=await Promise.all(raw.map(async code=>{try{return{ok:true,code,value:await quoteOne(code,env)}}catch(e){return{ok:false,code,error:e.message||'quote_failed'}}}));const data=settled.filter(x=>x.ok).map(x=>x.value),errors=settled.filter(x=>!x.ok).map(x=>({code:x.code,market:marketOf(x.code),error:x.error}));return json({data,errors,meta:{gateway:'v74',schemaVersion:2,requested:raw.length,returned:data.length,partial:!!data.length&&!!errors.length,fetchedAt:Date.now(),cacheTtlSeconds:QUOTE_TTL,staleFallbackSeconds:STALE_TTL}},data.length?200:502,env)}
function normalizeSeries(payload,key,limit=180){const s=payload?.[key];if(!s)return[];return Object.entries(s).slice(0,limit).map(([date,v])=>({ts:new Date(`${date}T00:00:00Z`).getTime(),o:n(v['1. open']),h:n(v['2. high']),l:n(v['3. low']),c:n(v['4. close']),v:n(v['5. volume'])})).filter(p=>p.c!=null).sort((a,b)=>a.ts-b.ts)}
function historySpec(p){p=String(p||'1d').toLowerCase();if(['1d','daily'].includes(p))return{period:'1d',fn:'TIME_SERIES_DAILY',key:'Time Series (Daily)',params:{outputsize:'compact'}};if(['1w','weekly'].includes(p))return{period:'1w',fn:'TIME_SERIES_WEEKLY',key:'Weekly Time Series',params:{}};if(['1m','monthly'].includes(p))return{period:'1m',fn:'TIME_SERIES_MONTHLY',key:'Monthly Time Series',params:{}};return null}
async function domesticTest(request,env){const u=new URL(request.url),code=(u.searchParams.get('code')||'600519').trim().toUpperCase(),market=marketOf(code);if(!['CN','HK'].includes(market))return json({ok:false,error:'domestic_test_supports_cn_hk'},400,env);try{const quote=market==='CN'&&env.STOCKTODAY_TOKEN?await stockTodayAQuoteCached(code,env):market==='CN'&&env.TUSHARE_TOKEN?await tushareAQuoteCached(code,env):await externalProxyQuote(code,market,env);return json({ok:true,mode:quote._staleCache?'stale_cache':(market==='CN'&&env.STOCKTODAY_TOKEN?'stocktoday':market==='CN'&&env.TUSHARE_TOKEN?'tushare':'domestic_provider'),market,quote,note:quote._staleCache?'上游不可用，当前为最近一次真实缓存。':(market==='CN'&&env.STOCKTODAY_TOKEN?'StockToday rt_k 返回；时效取决于第三方接口权限。':market==='CN'&&env.TUSHARE_TOKEN?'Tushare rt_k 返回；时效取决于 Tushare 接口权限。':'国内 Provider 返回；时效取决于上游授权。')},200,env)}catch(e){return json({ok:false,market,error:e.message,providerConfigured:!!(market==='CN'?(env.STOCKTODAY_TOKEN||env.TUSHARE_TOKEN||env.CN_PROVIDER_URL):env.HK_PROVIDER_URL)},503,env)}}
async function tushareHistory(code,period,env){if(!env.TUSHARE_TOKEN)throw new Error('tushare_not_configured');const api=period==='1w'?'weekly':period==='1m'?'monthly':'daily',end=new Date(),start=new Date(end.getTime()-540*86400000),fmt=d=>d.toISOString().slice(0,10).replaceAll('-',''),ts=tushareCode(code),r=await fetch('https://api.tushare.pro',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_name:api,token:env.TUSHARE_TOKEN,params:{ts_code:ts,start_date:fmt(start),end_date:fmt(end)},fields:'ts_code,trade_date,open,high,low,close,vol'})});if(!r.ok)throw new Error('tushare_http_'+r.status);const p=await r.json();if(p?.code&&p.code!==0)throw new Error('tushare_'+(p.msg||'api_error'));const fields=p?.data?.fields||[],rows=p?.data?.items||[],points=rows.map(row=>{const q=Object.fromEntries(fields.map((f,i)=>[f,row[i]]));return{ts:new Date(String(q.trade_date).replace(/(\\d{4})(\\d{2})(\\d{2})/,'$1-$2-$3')+'T00:00:00Z').getTime(),o:n(q.open),h:n(q.high),l:n(q.low),c:n(q.close),v:n(q.vol)}}).filter(x=>x.c!=null).sort((a,b)=>a.ts-b.ts).slice(-180);if(!points.length)throw new Error('tushare_history_unavailable');return{code,period,market:'CN',provider:'tushare_'+api,source:'tushare',currency:'CNY',isMock:false,points,meta:{schemaVersion:2,count:points.length,fetchedAt:Date.now(),cacheTtlSeconds:HISTORY_TTL}}}
async function history(request,env){const u=new URL(request.url),code=(u.searchParams.get('code')||'').trim().toUpperCase(),spec=historySpec(u.searchParams.get('period'));if(!code)return json({error:'missing_code'},400,env);if(!['US','CN'].includes(marketOf(code)))return json({error:'history_provider_not_configured'},501,env);if(marketOf(code)==='CN'&&env.TUSHARE_TOKEN){try{return json(await edgeCached('history:TUSHARE:'+code+':'+spec.period,HISTORY_TTL,()=>tushareHistory(code,spec.period,env)),200,env)}catch(e){return json({error:e.message||'history_failed',code,provider:'tushare'},502,env)}}if(marketOf(code)!=='US')return json({error:'history_provider_not_configured'},501,env);if(!spec)return json({error:'unsupported_period',supported:['1d','1w','1m']},400,env);try{let result;if(env.TWELVE_DATA_API_KEY){try{result=await edgeCached(`history:TD:${code}:${spec.period}`,HISTORY_TTL,async()=>{const interval=spec.period==='1d'?'1day':spec.period==='1w'?'1week':'1month',p=await tdGet('/time_series',{symbol:code,interval,outputsize:'180',order:'asc'},env.TWELVE_DATA_API_KEY),points=(p.values||[]).map(v=>({ts:new Date(v.datetime+'Z').getTime(),o:n(v.open),h:n(v.high),l:n(v.low),c:n(v.close),v:n(v.volume)})).filter(x=>x.c!=null);if(!points.length)throw new Error('history_unavailable');return{code,period:spec.period,market:'US',provider:'twelve_data',source:'twelve_data',currency:'USD',isMock:false,points,meta:{schemaVersion:2,count:points.length,fetchedAt:Date.now(),cacheTtlSeconds:HISTORY_TTL}}})}catch{result=null}}if(!result){if(!env.ALPHA_VANTAGE_API_KEY)throw new Error('history_provider_not_configured');result=await edgeCached(`history:AV:${code}:${spec.period}`,HISTORY_TTL,async()=>{const p=await avQuery({function:spec.fn,symbol:code,...spec.params},env.ALPHA_VANTAGE_API_KEY),points=normalizeSeries(p,spec.key);if(!points.length)throw new Error('history_unavailable');return{code,period:spec.period,market:'US',provider:'alpha_vantage',source:'alpha_vantage',currency:'USD',isMock:false,points,meta:{schemaVersion:2,count:points.length,fetchedAt:Date.now(),cacheTtlSeconds:HISTORY_TTL}}})}return json(result,200,env)}catch(e){return json({error:e.message||'history_failed',code},502,env)}}
function parseCalendarPayload(p,m){const src=p?.markets?.[m]??p?.[m]??p?.dates??[];return Array.isArray(src)?src.filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(String(x))).map(String):[]}
async function calendar(request,env){const m=(new URL(request.url).searchParams.get('market')||'').toUpperCase();if(!['US','CN','HK','JP','KR','EU'].includes(m))return json({error:'unsupported_market'},400,env);if(!env.CALENDAR_JSON&&!env.CALENDAR_URL)return json({error:'calendar_not_configured'},501,env);try{const result=await edgeCached(`calendar:${m}`,CALENDAR_TTL,async()=>{let p;if(env.CALENDAR_JSON)p=JSON.parse(env.CALENDAR_JSON);else{const r=await fetch(env.CALENDAR_URL,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`calendar_http_${r.status}`);p=await r.json()}const dates=parseCalendarPayload(p,m);return{market:m,dates,source:env.CALENDAR_URL?'external_url':'env_json',fetchedAt:Date.now(),meta:{count:dates.length,cacheTtlSeconds:CALENDAR_TTL}}});return json(result,200,env)}catch(e){return json({error:e.message||'calendar_failed',market:m},502,env)}}
function providers(env){const usChain=['webull_sandbox(AAPL)',env.TWELVE_DATA_API_KEY?'twelve_data':null,env.ALPHA_VANTAGE_API_KEY?'alpha_vantage':null].filter(Boolean);return{US:{configured:true,provider:'webull_sandbox',sandbox:true,sandboxSymbols:['AAPL'],fallbacks:usChain.slice(1),quotes:true,history:(env.TWELVE_DATA_API_KEY||env.ALPHA_VANTAGE_API_KEY)?['1d','1w','1m']:[],market:'US'},CN:{configured:!!(env.STOCKTODAY_TOKEN||env.TUSHARE_TOKEN||env.CN_PROVIDER_URL),provider:env.STOCKTODAY_TOKEN?'stocktoday_rt_k':env.TUSHARE_TOKEN?'tushare_rt_k':env.CN_PROVIDER_URL?'cn_proxy':null,quotes:!!(env.TUSHARE_TOKEN||env.CN_PROVIDER_URL),history:[],market:'CN'},HK:{configured:!!env.HK_PROVIDER_URL,provider:'hk_proxy',quotes:!!env.HK_PROVIDER_URL,history:[],market:'HK'},JP:{configured:false,provider:null,quotes:false,history:[],market:'JP'},KR:{configured:false,provider:null,quotes:false,history:[],market:'KR'},EU:{configured:false,provider:null,quotes:false,history:[],market:'EU'}}}
function health(env){const p=providers(env),scope=Object.entries(p).filter(([,v])=>v.configured).map(([k])=>k);return{ok:true,service:'hangqing-wanxiang-gateway',version:'74',schemaVersion:2,providers:p,scope,ready:scope.length>0,limits:{quotesPerRequest:MAX_CODES},cache:{quotesSeconds:QUOTE_TTL,staleFallbackSeconds:STALE_TTL,historySeconds:HISTORY_TTL,calendarSeconds:CALENDAR_TTL},features:{webullSandbox:true,webullSandboxSymbols:['AAPL'],multiProvider:true,staleRealFallback:true,historyPeriods:['1d','1w','1m'],calendar:!!(env.CALENDAR_JSON||env.CALENDAR_URL)},fetchedAt:Date.now()}}
function ready(env){const h=health(env),us=h.providers.US;return{ok:h.ready,version:h.version,schemaVersion:2,liveMarkets:h.scope,US:{configured:us.configured,provider:us.provider,sandbox:us.sandbox,sandboxSymbols:us.sandboxSymbols,fallbacks:us.fallbacks,quotes:us.quotes,history:us.history},note:'Webull sandbox is development-only and currently limited to AAPL. Production freshness depends on provider entitlement.',fetchedAt:Date.now()}}
async function webullTest(env){try{const q=await wbQuote('AAPL',env);return json({ok:true,mode:'sandbox',quote:q,note:'Development test only; not production entitlement.'},200,env)}catch(e){return json({ok:false,mode:'sandbox',error:e.message,note:'Check Webull sandbox authentication/permission.'},502,env)}}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(env)});const u=new URL(request.url);if(u.pathname==='/health'&&request.method==='GET')return json(health(env),200,env);if(u.pathname==='/ready'&&request.method==='GET')return json(ready(env),200,env);if(u.pathname==='/test/webull'&&request.method==='GET')return webullTest(env);if(u.pathname==='/quotes'&&request.method==='GET')return quotes(request,env);if(u.pathname==='/history'&&request.method==='GET')return history(request,env);if(u.pathname==='/test/domestic'&&request.method==='GET')return domesticTest(request,env);if(u.pathname==='/test/stocktoday-auth'&&request.method==='GET')return stockTodayAuthTest(request,env);if(u.pathname==='/calendar'&&request.method==='GET')return calendar(request,env);return json({error:'not_found'},404,env)}};
